{{- if .Values.lagoonLogs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-source-lagoon
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
data:
  lagoon.conf: |
    # lagoon logs from rabbitmq
    <source>
      @type         rabbitmq
      @id           in_lagoon
      tag           "lagoon.#{ENV['CLUSTER_NAME']}.lagoon"
      host          "#{ENV['RABBITMQ_HOST']}"
      user          "#{ENV['RABBITMQ_USER']}"
      pass          "#{ENV['RABBITMQ_PASSWORD']}"
      # logstash default vhost
      vhost         /
      exchange      lagoon-logs
      exchange_type direct
      routing_key   ""
      queue         logs-dispatcher
      durable       true
    </source>
{{- end }}
