// flow-typed signature: 2dc513977299069da5da9d0ff1cbaa5c
// flow-typed version: <<STUB>>/dotenv-extended_v^1.0.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-extended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-extended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-extended/config' {
  declare module.exports: any;
}

declare module 'dotenv-extended/lib/config' {
  declare module.exports: any;
}

declare module 'dotenv-extended/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-extended/config.js' {
  declare module.exports: $Exports<'dotenv-extended/config'>;
}
declare module 'dotenv-extended/lib/config.js' {
  declare module.exports: $Exports<'dotenv-extended/lib/config'>;
}
declare module 'dotenv-extended/lib/index.js' {
  declare module.exports: $Exports<'dotenv-extended/lib/index'>;
}
