// flow-typed signature: 6d5bd25389142831029c14e332dbf52e
// flow-typed version: <<STUB>>/express-graphql_v^0.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-graphql/dist/index' {
  declare module.exports: any;
}

declare module 'express-graphql/dist/parseBody' {
  declare module.exports: any;
}

declare module 'express-graphql/dist/renderGraphiQL' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-graphql/dist/index.js' {
  declare module.exports: $Exports<'express-graphql/dist/index'>;
}
declare module 'express-graphql/dist/parseBody.js' {
  declare module.exports: $Exports<'express-graphql/dist/parseBody'>;
}
declare module 'express-graphql/dist/renderGraphiQL.js' {
  declare module.exports: $Exports<'express-graphql/dist/renderGraphiQL'>;
}
