// flow-typed signature: 896b7461543718903e99f49ba97ada99
// flow-typed version: <<STUB>>/morgan_v^1.7.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'morgan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'morgan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'morgan/index' {
  declare module.exports: $Exports<'morgan'>;
}
declare module 'morgan/index.js' {
  declare module.exports: $Exports<'morgan'>;
}
