// flow-typed signature: d8e1605e67ef90b7c8aecbd257b5e2ec
// flow-typed version: <<STUB>>/sshpk_v1.13.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sshpk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sshpk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sshpk/lib/algs' {
  declare module.exports: any;
}

declare module 'sshpk/lib/certificate' {
  declare module.exports: any;
}

declare module 'sshpk/lib/dhe' {
  declare module.exports: any;
}

declare module 'sshpk/lib/ed-compat' {
  declare module.exports: any;
}

declare module 'sshpk/lib/errors' {
  declare module.exports: any;
}

declare module 'sshpk/lib/fingerprint' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/auto' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/openssh-cert' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/pem' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/pkcs1' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/pkcs8' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/rfc4253' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/ssh-private' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/ssh' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/x509-pem' {
  declare module.exports: any;
}

declare module 'sshpk/lib/formats/x509' {
  declare module.exports: any;
}

declare module 'sshpk/lib/identity' {
  declare module.exports: any;
}

declare module 'sshpk/lib/index' {
  declare module.exports: any;
}

declare module 'sshpk/lib/key' {
  declare module.exports: any;
}

declare module 'sshpk/lib/private-key' {
  declare module.exports: any;
}

declare module 'sshpk/lib/signature' {
  declare module.exports: any;
}

declare module 'sshpk/lib/ssh-buffer' {
  declare module.exports: any;
}

declare module 'sshpk/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sshpk/lib/algs.js' {
  declare module.exports: $Exports<'sshpk/lib/algs'>;
}
declare module 'sshpk/lib/certificate.js' {
  declare module.exports: $Exports<'sshpk/lib/certificate'>;
}
declare module 'sshpk/lib/dhe.js' {
  declare module.exports: $Exports<'sshpk/lib/dhe'>;
}
declare module 'sshpk/lib/ed-compat.js' {
  declare module.exports: $Exports<'sshpk/lib/ed-compat'>;
}
declare module 'sshpk/lib/errors.js' {
  declare module.exports: $Exports<'sshpk/lib/errors'>;
}
declare module 'sshpk/lib/fingerprint.js' {
  declare module.exports: $Exports<'sshpk/lib/fingerprint'>;
}
declare module 'sshpk/lib/formats/auto.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/auto'>;
}
declare module 'sshpk/lib/formats/openssh-cert.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/openssh-cert'>;
}
declare module 'sshpk/lib/formats/pem.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/pem'>;
}
declare module 'sshpk/lib/formats/pkcs1.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/pkcs1'>;
}
declare module 'sshpk/lib/formats/pkcs8.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/pkcs8'>;
}
declare module 'sshpk/lib/formats/rfc4253.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/rfc4253'>;
}
declare module 'sshpk/lib/formats/ssh-private.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/ssh-private'>;
}
declare module 'sshpk/lib/formats/ssh.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/ssh'>;
}
declare module 'sshpk/lib/formats/x509-pem.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/x509-pem'>;
}
declare module 'sshpk/lib/formats/x509.js' {
  declare module.exports: $Exports<'sshpk/lib/formats/x509'>;
}
declare module 'sshpk/lib/identity.js' {
  declare module.exports: $Exports<'sshpk/lib/identity'>;
}
declare module 'sshpk/lib/index.js' {
  declare module.exports: $Exports<'sshpk/lib/index'>;
}
declare module 'sshpk/lib/key.js' {
  declare module.exports: $Exports<'sshpk/lib/key'>;
}
declare module 'sshpk/lib/private-key.js' {
  declare module.exports: $Exports<'sshpk/lib/private-key'>;
}
declare module 'sshpk/lib/signature.js' {
  declare module.exports: $Exports<'sshpk/lib/signature'>;
}
declare module 'sshpk/lib/ssh-buffer.js' {
  declare module.exports: $Exports<'sshpk/lib/ssh-buffer'>;
}
declare module 'sshpk/lib/utils.js' {
  declare module.exports: $Exports<'sshpk/lib/utils'>;
}
