// Code generated by go-bindata. (@generated) DO NOT EDIT.

 //Package lgraphql generated by go-bindata.// sources:
// _lgraphql/projectNotifications.graphql
package lgraphql

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __lgraphqlProjectnotificationsGraphql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xcc\x92\xc1\x4a\xc4\x30\x10\x86\xcf\xf6\x29\x46\xf0\xb0\x5e\xfa\x00\xde\x54\x3c\xba\x07\x5b\xf0\xb8\xc4\x74\xd6\x8c\x6d\x67\x6a\x32\x2a\x41\xfa\xee\x92\x96\xc5\xb6\x2a\x45\x50\xd8\xff\x94\xfc\xf9\x66\xf8\x93\xc9\xf3\x0b\xfa\x08\x9b\x0c\xe0\x8c\x4d\x8b\x17\x50\xa8\x27\x7e\x3c\xcd\xce\xe1\x3d\x03\x00\xe8\xbc\x3c\xa1\xd5\xab\xb8\x35\x2d\x6e\x06\x2b\x69\x84\x87\x9a\xc1\x3b\xe0\x49\x54\xcd\xb0\xcf\x8d\x28\xed\xc9\x1a\x25\xe1\x30\xe1\x93\xf2\x3c\x07\x61\xd8\x4e\x90\xa2\x31\xb6\x5e\x60\x49\xbb\x9d\xc6\x0e\x67\x9d\x0f\x7a\xc3\x07\x27\x52\x7f\xf1\xbf\x85\xad\x33\xcc\xd8\xcc\xfc\x7e\x2d\xd4\x9d\xd8\x1a\xf5\xda\x19\x3d\xb6\x64\x37\xad\xa1\xe6\x77\xa1\x30\x95\x5c\x56\x95\xc7\x10\xd6\x93\xad\x26\xb8\x25\xeb\x25\xc8\x5e\x4b\x34\xed\x72\xc0\x7f\xf5\x3e\xab\x29\xee\xc7\x4e\xff\x39\x1e\x61\x45\xd6\x32\x76\xcb\xb3\x93\xe9\x17\x2f\xf0\x15\x3d\x69\x2c\x9d\xc7\xe0\xa4\xa9\x7e\xb8\xc7\xb8\xea\xb3\xfe\x23\x00\x00\xff\xff\x7f\x5a\x0f\xed\x8c\x03\x00\x00")

func _lgraphqlProjectnotificationsGraphqlBytes() ([]byte, error) {
	return bindataRead(
		__lgraphqlProjectnotificationsGraphql,
		"_lgraphql/projectNotifications.graphql",
	)
}

func _lgraphqlProjectnotificationsGraphql() (*asset, error) {
	bytes, err := _lgraphqlProjectnotificationsGraphqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "_lgraphql/projectNotifications.graphql", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"_lgraphql/projectNotifications.graphql": _lgraphqlProjectnotificationsGraphql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"_lgraphql": &bintree{nil, map[string]*bintree{
		"projectNotifications.graphql": &bintree{_lgraphqlProjectnotificationsGraphql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
