version: '3.2'

volumes:
  broker: {}

services:
  api-db:
    image: uselagoon/mysql-8.0:latest
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
      - MYSQL_DATABASE=infrastructure
  keycloak:
    environment:
      - DB_VENDOR=mysql
      - LAGOON_DB_VENDOR=mysql
  keycloak-db:
    image: uselagoon/mysql-8.0:latest
    environment:
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
      - MYSQL_DATABASE=keycloak