#! /bin/bash

# simple readiness check to see if a late-running entrypoint has completed

function version_check() {
  test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
}

function file_check() {
  test -f /tmp/ready
}

VERSION="${LAGOON_VERSION}:1"
if version_check $VERSION 1.8.2 || [[ "${LAGOON_VERSION}" = "development" ]]; then
  file_check
else
  # older version, just exit
  exit 0
fi
