// flow-typed signature: 0d173846f6286a78d0e0a1aeab186523
// flow-typed version: <<STUB>>/@amazee/persistgraphql_v^0.3.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@amazee/persistgraphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@amazee/persistgraphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@amazee/persistgraphql/lib/index' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/binary' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/common' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/extractFromAST' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/extractFromJS' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/ExtractGQL' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/network_interface/ApolloNetworkInterface' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/src/queryTransformers' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/test/extractFromAST' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/test/extractFromJS' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/test/index' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/test/network_interface/ApolloNetworkInterface' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/test/queryTransformers' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/lib/test/tests' {
  declare module.exports: any;
}

declare module '@amazee/persistgraphql/test/fixtures/single_fragment_js/code' {
  declare module.exports: any;
}

// Filename aliases
declare module '@amazee/persistgraphql/lib/index.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/index'>;
}
declare module '@amazee/persistgraphql/lib/src/binary.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/binary'>;
}
declare module '@amazee/persistgraphql/lib/src/common.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/common'>;
}
declare module '@amazee/persistgraphql/lib/src/extractFromAST.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/extractFromAST'>;
}
declare module '@amazee/persistgraphql/lib/src/extractFromJS.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/extractFromJS'>;
}
declare module '@amazee/persistgraphql/lib/src/ExtractGQL.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/ExtractGQL'>;
}
declare module '@amazee/persistgraphql/lib/src/network_interface/ApolloNetworkInterface.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/network_interface/ApolloNetworkInterface'>;
}
declare module '@amazee/persistgraphql/lib/src/queryTransformers.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/src/queryTransformers'>;
}
declare module '@amazee/persistgraphql/lib/test/extractFromAST.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/test/extractFromAST'>;
}
declare module '@amazee/persistgraphql/lib/test/extractFromJS.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/test/extractFromJS'>;
}
declare module '@amazee/persistgraphql/lib/test/index.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/test/index'>;
}
declare module '@amazee/persistgraphql/lib/test/network_interface/ApolloNetworkInterface.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/test/network_interface/ApolloNetworkInterface'>;
}
declare module '@amazee/persistgraphql/lib/test/queryTransformers.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/test/queryTransformers'>;
}
declare module '@amazee/persistgraphql/lib/test/tests.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/lib/test/tests'>;
}
declare module '@amazee/persistgraphql/test/fixtures/single_fragment_js/code.js' {
  declare module.exports: $Exports<'@amazee/persistgraphql/test/fixtures/single_fragment_js/code'>;
}
