// flow-typed signature: f38afb0201bb21777fb0d66be9309d18
// flow-typed version: <<STUB>>/@amazee/react-scripts_v0.0.58/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@amazee/react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@amazee/react-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@amazee/react-scripts/bin/react-scripts' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/mock/drupal' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/paths' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/polyfills' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/webpack/webpack.base' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/webpack/webpack.dev' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/webpack/webpack.dll' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/webpack/webpack.prod' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/config/webpack/webpack.resolve' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/scripts/build-dll' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/scripts/build' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/scripts/dev' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/scripts/lint' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/scripts/start' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/scripts/test' {
  declare module.exports: any;
}

declare module '@amazee/react-scripts/utils/createJestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module '@amazee/react-scripts/bin/react-scripts.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/bin/react-scripts'>;
}
declare module '@amazee/react-scripts/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/jest/babelTransform'>;
}
declare module '@amazee/react-scripts/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/jest/cssTransform'>;
}
declare module '@amazee/react-scripts/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/jest/fileTransform'>;
}
declare module '@amazee/react-scripts/config/mock/drupal.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/mock/drupal'>;
}
declare module '@amazee/react-scripts/config/paths.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/paths'>;
}
declare module '@amazee/react-scripts/config/polyfills.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/polyfills'>;
}
declare module '@amazee/react-scripts/config/webpack/webpack.base.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/webpack/webpack.base'>;
}
declare module '@amazee/react-scripts/config/webpack/webpack.dev.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/webpack/webpack.dev'>;
}
declare module '@amazee/react-scripts/config/webpack/webpack.dll.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/webpack/webpack.dll'>;
}
declare module '@amazee/react-scripts/config/webpack/webpack.prod.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/webpack/webpack.prod'>;
}
declare module '@amazee/react-scripts/config/webpack/webpack.resolve.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/config/webpack/webpack.resolve'>;
}
declare module '@amazee/react-scripts/scripts/build-dll.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/scripts/build-dll'>;
}
declare module '@amazee/react-scripts/scripts/build.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/scripts/build'>;
}
declare module '@amazee/react-scripts/scripts/dev.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/scripts/dev'>;
}
declare module '@amazee/react-scripts/scripts/lint.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/scripts/lint'>;
}
declare module '@amazee/react-scripts/scripts/start.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/scripts/start'>;
}
declare module '@amazee/react-scripts/scripts/test.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/scripts/test'>;
}
declare module '@amazee/react-scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'@amazee/react-scripts/utils/createJestConfig'>;
}
