#!/bin/sh
# This script calls the /ping endpoing of the php-fpm, if the return code is 0, the php-fpm has correctly started
SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET /usr/bin/cgi-fcgi -bind -connect 127.0.0.1:9000