apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: lagoon-build-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lagoon-kbd-leader-election-role
  namespace: lagoon-build-deploy
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: lagoon-kbd-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoonbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoonbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoontasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoontasks/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagoon-kbd-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lagoon-kbd-leader-election-rolebinding
  namespace: lagoon-build-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lagoon-kbd-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: lagoon-build-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lagoon-kbd-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lagoon-kbd-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: lagoon-build-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lagoon-kbd-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lagoon-kbd-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: lagoon-build-deploy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: lagoon-kbd-controller-manager-metrics-service
  namespace: lagoon-build-deploy
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: lagoon-kbd-controller-manager
  namespace: lagoon-build-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --is-openshift
        command:
        - /manager
        env:
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
        - name: RABBITMQ_HOSTNAME
          value: 172.17.0.1:5672
        - name: LAGOON_TARGET_NAME
          value: ci-local-openshift-os
        - name: OVERRIDE_BUILD_DEPLOY_DIND_IMAGE
          value: 172.17.0.1:5000/lagoon/oc-build-deploy-dind:latest
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: amazeeio/lagoon-builddeploy:v0.1.4
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
