#!/bin/sh
KEYCLOAK_USER=$KEYCLOAK_ADMIN_USER KEYCLOAK_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN_USER KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD /lagoon/kc-startup.sh "$@"
