// flow-typed signature: 53d029c66ef4bc9f899a3d89723e39ff
// flow-typed version: <<STUB>>/nano_v^6.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nano'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nano' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nano/examples/bulk_transform' {
  declare module.exports: any;
}

declare module 'nano/examples/express' {
  declare module.exports: any;
}

declare module 'nano/examples/lazy_creation_of_views' {
  declare module.exports: any;
}

declare module 'nano/examples/lazy_db_creation_and_replication' {
  declare module.exports: any;
}

declare module 'nano/examples/pipe' {
  declare module.exports: any;
}

declare module 'nano/lib/logger' {
  declare module.exports: any;
}

declare module 'nano/lib/nano' {
  declare module.exports: any;
}

declare module 'nano/tests/helpers/index' {
  declare module.exports: any;
}

declare module 'nano/tests/helpers/integration' {
  declare module.exports: any;
}

declare module 'nano/tests/helpers/unit' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/attachment/destroy' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/attachment/get' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/attachment/insert' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/attachment/pipe' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/attachment/update' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/changes' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/compact' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/create-and-destroy' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/follow' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/get' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/list' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/replicate' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/database/replicator' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/atomic' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/compact' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/list' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/multiple' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/query' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/search' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/design/show' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/bulk' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/copy' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/destroy' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/fetch_revs' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/fetch' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/get' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/head' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/insert' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/list' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/document/update' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/multipart/get' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/multipart/insert' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/shared/config' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/shared/cookie' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/shared/error' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/shared/headers' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/shared/log' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/shared/nano' {
  declare module.exports: any;
}

declare module 'nano/tests/integration/util/uuid' {
  declare module.exports: any;
}

declare module 'nano/tests/intercept/design/search' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/attachment/destroy' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/attachment/get' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/attachment/insert' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/changes' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/compact' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/create' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/destroy' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/follow' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/get' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/list' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/replicate' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/replicator' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/database/updates' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/atomic' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/compact' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/list' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/search' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/show' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/spatial' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/design/view' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/document/bulk' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/document/copy' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/multipart/get' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/multipart/insert' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/shared/error' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/shared/follow-updates' {
  declare module.exports: any;
}

declare module 'nano/tests/unit/shared/jar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nano/examples/bulk_transform.js' {
  declare module.exports: $Exports<'nano/examples/bulk_transform'>;
}
declare module 'nano/examples/express.js' {
  declare module.exports: $Exports<'nano/examples/express'>;
}
declare module 'nano/examples/lazy_creation_of_views.js' {
  declare module.exports: $Exports<'nano/examples/lazy_creation_of_views'>;
}
declare module 'nano/examples/lazy_db_creation_and_replication.js' {
  declare module.exports: $Exports<'nano/examples/lazy_db_creation_and_replication'>;
}
declare module 'nano/examples/pipe.js' {
  declare module.exports: $Exports<'nano/examples/pipe'>;
}
declare module 'nano/lib/logger.js' {
  declare module.exports: $Exports<'nano/lib/logger'>;
}
declare module 'nano/lib/nano.js' {
  declare module.exports: $Exports<'nano/lib/nano'>;
}
declare module 'nano/tests/helpers/index.js' {
  declare module.exports: $Exports<'nano/tests/helpers/index'>;
}
declare module 'nano/tests/helpers/integration.js' {
  declare module.exports: $Exports<'nano/tests/helpers/integration'>;
}
declare module 'nano/tests/helpers/unit.js' {
  declare module.exports: $Exports<'nano/tests/helpers/unit'>;
}
declare module 'nano/tests/integration/attachment/destroy.js' {
  declare module.exports: $Exports<'nano/tests/integration/attachment/destroy'>;
}
declare module 'nano/tests/integration/attachment/get.js' {
  declare module.exports: $Exports<'nano/tests/integration/attachment/get'>;
}
declare module 'nano/tests/integration/attachment/insert.js' {
  declare module.exports: $Exports<'nano/tests/integration/attachment/insert'>;
}
declare module 'nano/tests/integration/attachment/pipe.js' {
  declare module.exports: $Exports<'nano/tests/integration/attachment/pipe'>;
}
declare module 'nano/tests/integration/attachment/update.js' {
  declare module.exports: $Exports<'nano/tests/integration/attachment/update'>;
}
declare module 'nano/tests/integration/database/changes.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/changes'>;
}
declare module 'nano/tests/integration/database/compact.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/compact'>;
}
declare module 'nano/tests/integration/database/create-and-destroy.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/create-and-destroy'>;
}
declare module 'nano/tests/integration/database/follow.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/follow'>;
}
declare module 'nano/tests/integration/database/get.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/get'>;
}
declare module 'nano/tests/integration/database/list.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/list'>;
}
declare module 'nano/tests/integration/database/replicate.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/replicate'>;
}
declare module 'nano/tests/integration/database/replicator.js' {
  declare module.exports: $Exports<'nano/tests/integration/database/replicator'>;
}
declare module 'nano/tests/integration/design/atomic.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/atomic'>;
}
declare module 'nano/tests/integration/design/compact.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/compact'>;
}
declare module 'nano/tests/integration/design/list.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/list'>;
}
declare module 'nano/tests/integration/design/multiple.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/multiple'>;
}
declare module 'nano/tests/integration/design/query.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/query'>;
}
declare module 'nano/tests/integration/design/search.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/search'>;
}
declare module 'nano/tests/integration/design/show.js' {
  declare module.exports: $Exports<'nano/tests/integration/design/show'>;
}
declare module 'nano/tests/integration/document/bulk.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/bulk'>;
}
declare module 'nano/tests/integration/document/copy.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/copy'>;
}
declare module 'nano/tests/integration/document/destroy.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/destroy'>;
}
declare module 'nano/tests/integration/document/fetch_revs.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/fetch_revs'>;
}
declare module 'nano/tests/integration/document/fetch.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/fetch'>;
}
declare module 'nano/tests/integration/document/get.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/get'>;
}
declare module 'nano/tests/integration/document/head.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/head'>;
}
declare module 'nano/tests/integration/document/insert.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/insert'>;
}
declare module 'nano/tests/integration/document/list.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/list'>;
}
declare module 'nano/tests/integration/document/update.js' {
  declare module.exports: $Exports<'nano/tests/integration/document/update'>;
}
declare module 'nano/tests/integration/multipart/get.js' {
  declare module.exports: $Exports<'nano/tests/integration/multipart/get'>;
}
declare module 'nano/tests/integration/multipart/insert.js' {
  declare module.exports: $Exports<'nano/tests/integration/multipart/insert'>;
}
declare module 'nano/tests/integration/shared/config.js' {
  declare module.exports: $Exports<'nano/tests/integration/shared/config'>;
}
declare module 'nano/tests/integration/shared/cookie.js' {
  declare module.exports: $Exports<'nano/tests/integration/shared/cookie'>;
}
declare module 'nano/tests/integration/shared/error.js' {
  declare module.exports: $Exports<'nano/tests/integration/shared/error'>;
}
declare module 'nano/tests/integration/shared/headers.js' {
  declare module.exports: $Exports<'nano/tests/integration/shared/headers'>;
}
declare module 'nano/tests/integration/shared/log.js' {
  declare module.exports: $Exports<'nano/tests/integration/shared/log'>;
}
declare module 'nano/tests/integration/shared/nano.js' {
  declare module.exports: $Exports<'nano/tests/integration/shared/nano'>;
}
declare module 'nano/tests/integration/util/uuid.js' {
  declare module.exports: $Exports<'nano/tests/integration/util/uuid'>;
}
declare module 'nano/tests/intercept/design/search.js' {
  declare module.exports: $Exports<'nano/tests/intercept/design/search'>;
}
declare module 'nano/tests/unit/attachment/destroy.js' {
  declare module.exports: $Exports<'nano/tests/unit/attachment/destroy'>;
}
declare module 'nano/tests/unit/attachment/get.js' {
  declare module.exports: $Exports<'nano/tests/unit/attachment/get'>;
}
declare module 'nano/tests/unit/attachment/insert.js' {
  declare module.exports: $Exports<'nano/tests/unit/attachment/insert'>;
}
declare module 'nano/tests/unit/database/changes.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/changes'>;
}
declare module 'nano/tests/unit/database/compact.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/compact'>;
}
declare module 'nano/tests/unit/database/create.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/create'>;
}
declare module 'nano/tests/unit/database/destroy.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/destroy'>;
}
declare module 'nano/tests/unit/database/follow.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/follow'>;
}
declare module 'nano/tests/unit/database/get.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/get'>;
}
declare module 'nano/tests/unit/database/list.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/list'>;
}
declare module 'nano/tests/unit/database/replicate.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/replicate'>;
}
declare module 'nano/tests/unit/database/replicator.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/replicator'>;
}
declare module 'nano/tests/unit/database/updates.js' {
  declare module.exports: $Exports<'nano/tests/unit/database/updates'>;
}
declare module 'nano/tests/unit/design/atomic.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/atomic'>;
}
declare module 'nano/tests/unit/design/compact.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/compact'>;
}
declare module 'nano/tests/unit/design/list.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/list'>;
}
declare module 'nano/tests/unit/design/search.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/search'>;
}
declare module 'nano/tests/unit/design/show.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/show'>;
}
declare module 'nano/tests/unit/design/spatial.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/spatial'>;
}
declare module 'nano/tests/unit/design/view.js' {
  declare module.exports: $Exports<'nano/tests/unit/design/view'>;
}
declare module 'nano/tests/unit/document/bulk.js' {
  declare module.exports: $Exports<'nano/tests/unit/document/bulk'>;
}
declare module 'nano/tests/unit/document/copy.js' {
  declare module.exports: $Exports<'nano/tests/unit/document/copy'>;
}
declare module 'nano/tests/unit/multipart/get.js' {
  declare module.exports: $Exports<'nano/tests/unit/multipart/get'>;
}
declare module 'nano/tests/unit/multipart/insert.js' {
  declare module.exports: $Exports<'nano/tests/unit/multipart/insert'>;
}
declare module 'nano/tests/unit/shared/error.js' {
  declare module.exports: $Exports<'nano/tests/unit/shared/error'>;
}
declare module 'nano/tests/unit/shared/follow-updates.js' {
  declare module.exports: $Exports<'nano/tests/unit/shared/follow-updates'>;
}
declare module 'nano/tests/unit/shared/jar.js' {
  declare module.exports: $Exports<'nano/tests/unit/shared/jar'>;
}
