// flow-typed signature: 2c6e6ff7ad0b962f3c754dc69a3ed3bb
// flow-typed version: <<STUB>>/node-fetch_v^1.6.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-fetch/lib/body' {
  declare module.exports: any;
}

declare module 'node-fetch/lib/fetch-error' {
  declare module.exports: any;
}

declare module 'node-fetch/lib/headers' {
  declare module.exports: any;
}

declare module 'node-fetch/lib/request' {
  declare module.exports: any;
}

declare module 'node-fetch/lib/response' {
  declare module.exports: any;
}

declare module 'node-fetch/test/server' {
  declare module.exports: any;
}

declare module 'node-fetch/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-fetch/index' {
  declare module.exports: $Exports<'node-fetch'>;
}
declare module 'node-fetch/index.js' {
  declare module.exports: $Exports<'node-fetch'>;
}
declare module 'node-fetch/lib/body.js' {
  declare module.exports: $Exports<'node-fetch/lib/body'>;
}
declare module 'node-fetch/lib/fetch-error.js' {
  declare module.exports: $Exports<'node-fetch/lib/fetch-error'>;
}
declare module 'node-fetch/lib/headers.js' {
  declare module.exports: $Exports<'node-fetch/lib/headers'>;
}
declare module 'node-fetch/lib/request.js' {
  declare module.exports: $Exports<'node-fetch/lib/request'>;
}
declare module 'node-fetch/lib/response.js' {
  declare module.exports: $Exports<'node-fetch/lib/response'>;
}
declare module 'node-fetch/test/server.js' {
  declare module.exports: $Exports<'node-fetch/test/server'>;
}
declare module 'node-fetch/test/test.js' {
  declare module.exports: $Exports<'node-fetch/test/test'>;
}
