// flow-typed signature: 9fc47f9afb07f70bb687d0302bc97c59
// flow-typed version: <<STUB>>/table_v^4.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'table/dist/alignString' {
  declare module.exports: any;
}

declare module 'table/dist/alignTableData' {
  declare module.exports: any;
}

declare module 'table/dist/calculateCellHeight' {
  declare module.exports: any;
}

declare module 'table/dist/calculateCellWidthIndex' {
  declare module.exports: any;
}

declare module 'table/dist/calculateMaximumColumnWidthIndex' {
  declare module.exports: any;
}

declare module 'table/dist/calculateRowHeightIndex' {
  declare module.exports: any;
}

declare module 'table/dist/createStream' {
  declare module.exports: any;
}

declare module 'table/dist/drawBorder' {
  declare module.exports: any;
}

declare module 'table/dist/drawRow' {
  declare module.exports: any;
}

declare module 'table/dist/drawTable' {
  declare module.exports: any;
}

declare module 'table/dist/getBorderCharacters' {
  declare module.exports: any;
}

declare module 'table/dist/index' {
  declare module.exports: any;
}

declare module 'table/dist/makeConfig' {
  declare module.exports: any;
}

declare module 'table/dist/makeStreamConfig' {
  declare module.exports: any;
}

declare module 'table/dist/mapDataUsingRowHeightIndex' {
  declare module.exports: any;
}

declare module 'table/dist/padTableData' {
  declare module.exports: any;
}

declare module 'table/dist/stringifyTableData' {
  declare module.exports: any;
}

declare module 'table/dist/table' {
  declare module.exports: any;
}

declare module 'table/dist/truncateTableData' {
  declare module.exports: any;
}

declare module 'table/dist/validateConfig' {
  declare module.exports: any;
}

declare module 'table/dist/validateStreamConfig' {
  declare module.exports: any;
}

declare module 'table/dist/validateTableData' {
  declare module.exports: any;
}

declare module 'table/dist/wrapString' {
  declare module.exports: any;
}

declare module 'table/dist/wrapWord' {
  declare module.exports: any;
}

declare module 'table/test/alignString' {
  declare module.exports: any;
}

declare module 'table/test/calculateCellHeight' {
  declare module.exports: any;
}

declare module 'table/test/calculateCellWidthIndex' {
  declare module.exports: any;
}

declare module 'table/test/calculateMaximumColumnWidthIndex' {
  declare module.exports: any;
}

declare module 'table/test/calculateRowHeightIndex' {
  declare module.exports: any;
}

declare module 'table/test/config' {
  declare module.exports: any;
}

declare module 'table/test/configSamples' {
  declare module.exports: any;
}

declare module 'table/test/createStream' {
  declare module.exports: any;
}

declare module 'table/test/drawBorder' {
  declare module.exports: any;
}

declare module 'table/test/makeConfig' {
  declare module.exports: any;
}

declare module 'table/test/mapDataUsingRowHeightIndex' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/basic' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/cell_content_alignment' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/column_width' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/custom_border' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/draw_horizontal_line' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/expectTable' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/moon_mission' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/padding_cell_content' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/predefined_border_templates' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/streaming' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/text_truncating' {
  declare module.exports: any;
}

declare module 'table/test/README/usage/text_wrapping' {
  declare module.exports: any;
}

declare module 'table/test/streamConfig' {
  declare module.exports: any;
}

declare module 'table/test/streamConfigSamples' {
  declare module.exports: any;
}

declare module 'table/test/validateTableData' {
  declare module.exports: any;
}

declare module 'table/test/wrapString' {
  declare module.exports: any;
}

declare module 'table/test/wrapWord' {
  declare module.exports: any;
}

// Filename aliases
declare module 'table/dist/alignString.js' {
  declare module.exports: $Exports<'table/dist/alignString'>;
}
declare module 'table/dist/alignTableData.js' {
  declare module.exports: $Exports<'table/dist/alignTableData'>;
}
declare module 'table/dist/calculateCellHeight.js' {
  declare module.exports: $Exports<'table/dist/calculateCellHeight'>;
}
declare module 'table/dist/calculateCellWidthIndex.js' {
  declare module.exports: $Exports<'table/dist/calculateCellWidthIndex'>;
}
declare module 'table/dist/calculateMaximumColumnWidthIndex.js' {
  declare module.exports: $Exports<'table/dist/calculateMaximumColumnWidthIndex'>;
}
declare module 'table/dist/calculateRowHeightIndex.js' {
  declare module.exports: $Exports<'table/dist/calculateRowHeightIndex'>;
}
declare module 'table/dist/createStream.js' {
  declare module.exports: $Exports<'table/dist/createStream'>;
}
declare module 'table/dist/drawBorder.js' {
  declare module.exports: $Exports<'table/dist/drawBorder'>;
}
declare module 'table/dist/drawRow.js' {
  declare module.exports: $Exports<'table/dist/drawRow'>;
}
declare module 'table/dist/drawTable.js' {
  declare module.exports: $Exports<'table/dist/drawTable'>;
}
declare module 'table/dist/getBorderCharacters.js' {
  declare module.exports: $Exports<'table/dist/getBorderCharacters'>;
}
declare module 'table/dist/index.js' {
  declare module.exports: $Exports<'table/dist/index'>;
}
declare module 'table/dist/makeConfig.js' {
  declare module.exports: $Exports<'table/dist/makeConfig'>;
}
declare module 'table/dist/makeStreamConfig.js' {
  declare module.exports: $Exports<'table/dist/makeStreamConfig'>;
}
declare module 'table/dist/mapDataUsingRowHeightIndex.js' {
  declare module.exports: $Exports<'table/dist/mapDataUsingRowHeightIndex'>;
}
declare module 'table/dist/padTableData.js' {
  declare module.exports: $Exports<'table/dist/padTableData'>;
}
declare module 'table/dist/stringifyTableData.js' {
  declare module.exports: $Exports<'table/dist/stringifyTableData'>;
}
declare module 'table/dist/table.js' {
  declare module.exports: $Exports<'table/dist/table'>;
}
declare module 'table/dist/truncateTableData.js' {
  declare module.exports: $Exports<'table/dist/truncateTableData'>;
}
declare module 'table/dist/validateConfig.js' {
  declare module.exports: $Exports<'table/dist/validateConfig'>;
}
declare module 'table/dist/validateStreamConfig.js' {
  declare module.exports: $Exports<'table/dist/validateStreamConfig'>;
}
declare module 'table/dist/validateTableData.js' {
  declare module.exports: $Exports<'table/dist/validateTableData'>;
}
declare module 'table/dist/wrapString.js' {
  declare module.exports: $Exports<'table/dist/wrapString'>;
}
declare module 'table/dist/wrapWord.js' {
  declare module.exports: $Exports<'table/dist/wrapWord'>;
}
declare module 'table/test/alignString.js' {
  declare module.exports: $Exports<'table/test/alignString'>;
}
declare module 'table/test/calculateCellHeight.js' {
  declare module.exports: $Exports<'table/test/calculateCellHeight'>;
}
declare module 'table/test/calculateCellWidthIndex.js' {
  declare module.exports: $Exports<'table/test/calculateCellWidthIndex'>;
}
declare module 'table/test/calculateMaximumColumnWidthIndex.js' {
  declare module.exports: $Exports<'table/test/calculateMaximumColumnWidthIndex'>;
}
declare module 'table/test/calculateRowHeightIndex.js' {
  declare module.exports: $Exports<'table/test/calculateRowHeightIndex'>;
}
declare module 'table/test/config.js' {
  declare module.exports: $Exports<'table/test/config'>;
}
declare module 'table/test/configSamples.js' {
  declare module.exports: $Exports<'table/test/configSamples'>;
}
declare module 'table/test/createStream.js' {
  declare module.exports: $Exports<'table/test/createStream'>;
}
declare module 'table/test/drawBorder.js' {
  declare module.exports: $Exports<'table/test/drawBorder'>;
}
declare module 'table/test/makeConfig.js' {
  declare module.exports: $Exports<'table/test/makeConfig'>;
}
declare module 'table/test/mapDataUsingRowHeightIndex.js' {
  declare module.exports: $Exports<'table/test/mapDataUsingRowHeightIndex'>;
}
declare module 'table/test/README/usage/basic.js' {
  declare module.exports: $Exports<'table/test/README/usage/basic'>;
}
declare module 'table/test/README/usage/cell_content_alignment.js' {
  declare module.exports: $Exports<'table/test/README/usage/cell_content_alignment'>;
}
declare module 'table/test/README/usage/column_width.js' {
  declare module.exports: $Exports<'table/test/README/usage/column_width'>;
}
declare module 'table/test/README/usage/custom_border.js' {
  declare module.exports: $Exports<'table/test/README/usage/custom_border'>;
}
declare module 'table/test/README/usage/draw_horizontal_line.js' {
  declare module.exports: $Exports<'table/test/README/usage/draw_horizontal_line'>;
}
declare module 'table/test/README/usage/expectTable.js' {
  declare module.exports: $Exports<'table/test/README/usage/expectTable'>;
}
declare module 'table/test/README/usage/moon_mission.js' {
  declare module.exports: $Exports<'table/test/README/usage/moon_mission'>;
}
declare module 'table/test/README/usage/padding_cell_content.js' {
  declare module.exports: $Exports<'table/test/README/usage/padding_cell_content'>;
}
declare module 'table/test/README/usage/predefined_border_templates.js' {
  declare module.exports: $Exports<'table/test/README/usage/predefined_border_templates'>;
}
declare module 'table/test/README/usage/streaming.js' {
  declare module.exports: $Exports<'table/test/README/usage/streaming'>;
}
declare module 'table/test/README/usage/text_truncating.js' {
  declare module.exports: $Exports<'table/test/README/usage/text_truncating'>;
}
declare module 'table/test/README/usage/text_wrapping.js' {
  declare module.exports: $Exports<'table/test/README/usage/text_wrapping'>;
}
declare module 'table/test/streamConfig.js' {
  declare module.exports: $Exports<'table/test/streamConfig'>;
}
declare module 'table/test/streamConfigSamples.js' {
  declare module.exports: $Exports<'table/test/streamConfigSamples'>;
}
declare module 'table/test/validateTableData.js' {
  declare module.exports: $Exports<'table/test/validateTableData'>;
}
declare module 'table/test/wrapString.js' {
  declare module.exports: $Exports<'table/test/wrapString'>;
}
declare module 'table/test/wrapWord.js' {
  declare module.exports: $Exports<'table/test/wrapWord'>;
}
