mutation ClearApiData {
  # Remove everything from API

  # First, remove all relations between entities...
  RemoveAllNotificationsFromAllProjects: removeAllNotificationsFromAllProjects
  RemoveAllSshKeysFromAllUsers: removeAllSshKeysFromAllUsers

  # ...then delete the entities themselves
  DeleteAllEnvironments: deleteAllEnvironments
  DeleteAllNotificationSlacks: deleteAllNotificationSlacks
  DeleteAllNotificationRocketChats: deleteAllNotificationRocketChats
  DeleteAllOpenshifts: deleteAllOpenshifts
  DeleteAllProjects: deleteAllProjects
  DeleteAllSshKeys: deleteAllSshKeys
  DeleteAllUsers: deleteAllUsers
  DeleteAllBackups: deleteAllBackups
  DeleteAllGroups: deleteAllGroups
}
