#!/bin/sh
BASE=$(dirname $0)

echo "Linting file: .lagoon.yml"

yamllint -c ${BASE}/config/yamllint.yaml .lagoon.yml | cat

DOCKER_COMPOSE_YAML=$(cat .lagoon.yml | shyaml get-value docker-compose-yaml)
echo "Linting file: $(DOCKER_COMPOSE_YAML)"
yamllint -c ${BASE}/config/yamllint.yaml "$(DOCKER_COMPOSE_YAML)" | cat



echo "Validating files:"

${BASE}/validate-schema

echo "the file parsed was:"
grep -n . .lagoon.yml
