apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "mariadb-single.fullname" . }}"
  annotations:
    appuio.ch/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
    # storageClassName: {{ .Values.persistentStorageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
