{{ if .Capabilities.APIVersions.Has "backup.appuio.ch/v1alpha1/PreBackupPod" }}
apiVersion: backup.appuio.ch/v1alpha1
kind: PreBackupPod
metadata:
  name: {{ include "redis-persistent.fullname" . }}-prebackuppod
  labels:
    {{- include "redis-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "redis-persistent.annotations" . | nindent 4 }}
spec:
  backupCommand: /bin/sh -c "/bin/busybox tar -cf - -C {{ .Values.persistentStorage.path }} ."
  fileExtension: .{{ include "redis-persistent.fullname" . }}.tar
  pod:
    metadata:
      labels:
        prebackuppod: {{ include "redis-persistent.fullname" . }}
        {{- include "redis-persistent.labels" . | nindent 8 }}
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: lagoon.sh/service
                      operator: In
                      values:
                        - {{ include "redis-persistent.fullname" . }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - sleep
            - infinity
          envFrom:
            - configMapRef:
                name: lagoon-env
            - configMapRef:
                name: lagoon-api-vars
          image: imagecache.amazeeio.cloud/library/alpine
          imagePullPolicy: Always
          name: {{ include "redis-persistent.fullname" . }}-prebackuppod
          volumeMounts:
            - name: {{ include "redis-persistent.persistentStorageName" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
      volumes:
        - name: {{ include "redis-persistent.persistentStorageName" . }}
          persistentVolumeClaim:
            claimName: {{ include "redis-persistent.persistentStorageName" . }}
{{ end }}
