// flow-typed signature: 22527bc8d3379eac0db4cfac36bdc337
// flow-typed version: <<STUB>>/amqplib_vhttps://registry.npmjs.org/amqplib/-/amqplib-0.4.2.tgz/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amqplib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'amqplib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amqplib/callback_api' {
  declare module.exports: any;
}

declare module 'amqplib/channel_api' {
  declare module.exports: any;
}

declare module 'amqplib/examples/headers' {
  declare module.exports: any;
}

declare module 'amqplib/examples/ssl' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/emit_log_direct' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/emit_log_topic' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/emit_log' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/new_task' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/receive_logs_direct' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/receive_logs_topic' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/receive_logs' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/receive' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/rpc_client' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/rpc_server' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/send' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/callback_api/worker' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/emit_log_direct' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/emit_log_topic' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/emit_log' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/new_task' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/receive_logs_direct' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/receive_logs_topic' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/receive_logs' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/receive' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/rpc_client' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/rpc_server' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/send' {
  declare module.exports: any;
}

declare module 'amqplib/examples/tutorials/worker' {
  declare module.exports: any;
}

declare module 'amqplib/examples/waitForConfirms' {
  declare module.exports: any;
}

declare module 'amqplib/lib/api_args' {
  declare module.exports: any;
}

declare module 'amqplib/lib/bitset' {
  declare module.exports: any;
}

declare module 'amqplib/lib/callback_model' {
  declare module.exports: any;
}

declare module 'amqplib/lib/channel_model' {
  declare module.exports: any;
}

declare module 'amqplib/lib/channel' {
  declare module.exports: any;
}

declare module 'amqplib/lib/codec' {
  declare module.exports: any;
}

declare module 'amqplib/lib/connect' {
  declare module.exports: any;
}

declare module 'amqplib/lib/connection' {
  declare module.exports: any;
}

declare module 'amqplib/lib/credentials' {
  declare module.exports: any;
}

declare module 'amqplib/lib/defs' {
  declare module.exports: any;
}

declare module 'amqplib/lib/error' {
  declare module.exports: any;
}

declare module 'amqplib/lib/format' {
  declare module.exports: any;
}

declare module 'amqplib/lib/frame' {
  declare module.exports: any;
}

declare module 'amqplib/lib/heartbeat' {
  declare module.exports: any;
}

declare module 'amqplib/lib/mux' {
  declare module.exports: any;
}

declare module 'amqplib/test/bitset' {
  declare module.exports: any;
}

declare module 'amqplib/test/callback_api' {
  declare module.exports: any;
}

declare module 'amqplib/test/channel_api' {
  declare module.exports: any;
}

declare module 'amqplib/test/channel' {
  declare module.exports: any;
}

declare module 'amqplib/test/codec' {
  declare module.exports: any;
}

declare module 'amqplib/test/connect' {
  declare module.exports: any;
}

declare module 'amqplib/test/connection' {
  declare module.exports: any;
}

declare module 'amqplib/test/data' {
  declare module.exports: any;
}

declare module 'amqplib/test/frame' {
  declare module.exports: any;
}

declare module 'amqplib/test/mux' {
  declare module.exports: any;
}

declare module 'amqplib/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amqplib/callback_api.js' {
  declare module.exports: $Exports<'amqplib/callback_api'>;
}
declare module 'amqplib/channel_api.js' {
  declare module.exports: $Exports<'amqplib/channel_api'>;
}
declare module 'amqplib/examples/headers.js' {
  declare module.exports: $Exports<'amqplib/examples/headers'>;
}
declare module 'amqplib/examples/ssl.js' {
  declare module.exports: $Exports<'amqplib/examples/ssl'>;
}
declare module 'amqplib/examples/tutorials/callback_api/emit_log_direct.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/emit_log_direct'>;
}
declare module 'amqplib/examples/tutorials/callback_api/emit_log_topic.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/emit_log_topic'>;
}
declare module 'amqplib/examples/tutorials/callback_api/emit_log.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/emit_log'>;
}
declare module 'amqplib/examples/tutorials/callback_api/new_task.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/new_task'>;
}
declare module 'amqplib/examples/tutorials/callback_api/receive_logs_direct.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/receive_logs_direct'>;
}
declare module 'amqplib/examples/tutorials/callback_api/receive_logs_topic.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/receive_logs_topic'>;
}
declare module 'amqplib/examples/tutorials/callback_api/receive_logs.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/receive_logs'>;
}
declare module 'amqplib/examples/tutorials/callback_api/receive.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/receive'>;
}
declare module 'amqplib/examples/tutorials/callback_api/rpc_client.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/rpc_client'>;
}
declare module 'amqplib/examples/tutorials/callback_api/rpc_server.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/rpc_server'>;
}
declare module 'amqplib/examples/tutorials/callback_api/send.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/send'>;
}
declare module 'amqplib/examples/tutorials/callback_api/worker.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/callback_api/worker'>;
}
declare module 'amqplib/examples/tutorials/emit_log_direct.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/emit_log_direct'>;
}
declare module 'amqplib/examples/tutorials/emit_log_topic.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/emit_log_topic'>;
}
declare module 'amqplib/examples/tutorials/emit_log.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/emit_log'>;
}
declare module 'amqplib/examples/tutorials/new_task.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/new_task'>;
}
declare module 'amqplib/examples/tutorials/receive_logs_direct.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/receive_logs_direct'>;
}
declare module 'amqplib/examples/tutorials/receive_logs_topic.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/receive_logs_topic'>;
}
declare module 'amqplib/examples/tutorials/receive_logs.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/receive_logs'>;
}
declare module 'amqplib/examples/tutorials/receive.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/receive'>;
}
declare module 'amqplib/examples/tutorials/rpc_client.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/rpc_client'>;
}
declare module 'amqplib/examples/tutorials/rpc_server.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/rpc_server'>;
}
declare module 'amqplib/examples/tutorials/send.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/send'>;
}
declare module 'amqplib/examples/tutorials/worker.js' {
  declare module.exports: $Exports<'amqplib/examples/tutorials/worker'>;
}
declare module 'amqplib/examples/waitForConfirms.js' {
  declare module.exports: $Exports<'amqplib/examples/waitForConfirms'>;
}
declare module 'amqplib/lib/api_args.js' {
  declare module.exports: $Exports<'amqplib/lib/api_args'>;
}
declare module 'amqplib/lib/bitset.js' {
  declare module.exports: $Exports<'amqplib/lib/bitset'>;
}
declare module 'amqplib/lib/callback_model.js' {
  declare module.exports: $Exports<'amqplib/lib/callback_model'>;
}
declare module 'amqplib/lib/channel_model.js' {
  declare module.exports: $Exports<'amqplib/lib/channel_model'>;
}
declare module 'amqplib/lib/channel.js' {
  declare module.exports: $Exports<'amqplib/lib/channel'>;
}
declare module 'amqplib/lib/codec.js' {
  declare module.exports: $Exports<'amqplib/lib/codec'>;
}
declare module 'amqplib/lib/connect.js' {
  declare module.exports: $Exports<'amqplib/lib/connect'>;
}
declare module 'amqplib/lib/connection.js' {
  declare module.exports: $Exports<'amqplib/lib/connection'>;
}
declare module 'amqplib/lib/credentials.js' {
  declare module.exports: $Exports<'amqplib/lib/credentials'>;
}
declare module 'amqplib/lib/defs.js' {
  declare module.exports: $Exports<'amqplib/lib/defs'>;
}
declare module 'amqplib/lib/error.js' {
  declare module.exports: $Exports<'amqplib/lib/error'>;
}
declare module 'amqplib/lib/format.js' {
  declare module.exports: $Exports<'amqplib/lib/format'>;
}
declare module 'amqplib/lib/frame.js' {
  declare module.exports: $Exports<'amqplib/lib/frame'>;
}
declare module 'amqplib/lib/heartbeat.js' {
  declare module.exports: $Exports<'amqplib/lib/heartbeat'>;
}
declare module 'amqplib/lib/mux.js' {
  declare module.exports: $Exports<'amqplib/lib/mux'>;
}
declare module 'amqplib/test/bitset.js' {
  declare module.exports: $Exports<'amqplib/test/bitset'>;
}
declare module 'amqplib/test/callback_api.js' {
  declare module.exports: $Exports<'amqplib/test/callback_api'>;
}
declare module 'amqplib/test/channel_api.js' {
  declare module.exports: $Exports<'amqplib/test/channel_api'>;
}
declare module 'amqplib/test/channel.js' {
  declare module.exports: $Exports<'amqplib/test/channel'>;
}
declare module 'amqplib/test/codec.js' {
  declare module.exports: $Exports<'amqplib/test/codec'>;
}
declare module 'amqplib/test/connect.js' {
  declare module.exports: $Exports<'amqplib/test/connect'>;
}
declare module 'amqplib/test/connection.js' {
  declare module.exports: $Exports<'amqplib/test/connection'>;
}
declare module 'amqplib/test/data.js' {
  declare module.exports: $Exports<'amqplib/test/data'>;
}
declare module 'amqplib/test/frame.js' {
  declare module.exports: $Exports<'amqplib/test/frame'>;
}
declare module 'amqplib/test/mux.js' {
  declare module.exports: $Exports<'amqplib/test/mux'>;
}
declare module 'amqplib/test/util.js' {
  declare module.exports: $Exports<'amqplib/test/util'>;
}
