// flow-typed signature: b34e50fae7ffa8ef3a3235ddcc2881ea
// flow-typed version: <<STUB>>/loggly-winston-bulk_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loggly-winston-bulk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loggly-winston-bulk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loggly-winston-bulk/lib/winston-loggly' {
  declare module.exports: any;
}

declare module 'loggly-winston-bulk/test/winston-loggly-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loggly-winston-bulk/lib/winston-loggly.js' {
  declare module.exports: $Exports<'loggly-winston-bulk/lib/winston-loggly'>;
}
declare module 'loggly-winston-bulk/test/winston-loggly-test.js' {
  declare module.exports: $Exports<'loggly-winston-bulk/test/winston-loggly-test'>;
}
