// flow-typed signature: 3140924328fd3377db618d12f139652e
// flow-typed version: <<STUB>>/newman_v^3.3.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'newman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'newman' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'newman/bin/newman' {
  declare module.exports: any;
}

declare module 'newman/examples/find-unique-urls-in-run' {
  declare module.exports: any;
}

declare module 'newman/examples/parallel-collection-runs' {
  declare module.exports: any;
}

declare module 'newman/examples/read-collection-from-file' {
  declare module.exports: any;
}

declare module 'newman/examples/run-collections-in-directory' {
  declare module.exports: any;
}

declare module 'newman/lib/cli/index' {
  declare module.exports: any;
}

declare module 'newman/lib/config/index' {
  declare module.exports: any;
}

declare module 'newman/lib/config/process-env' {
  declare module.exports: any;
}

declare module 'newman/lib/config/rc-file' {
  declare module.exports: any;
}

declare module 'newman/lib/index' {
  declare module.exports: any;
}

declare module 'newman/lib/node-version-check/index' {
  declare module.exports: any;
}

declare module 'newman/lib/print/index' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/cli/cli-utils-symbols' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/cli/cli-utils' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/cli/index' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/emojitrain' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/html/index' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/json/index' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/junit/index' {
  declare module.exports: any;
}

declare module 'newman/lib/reporters/progress' {
  declare module.exports: any;
}

declare module 'newman/lib/run/export-file' {
  declare module.exports: any;
}

declare module 'newman/lib/run/index' {
  declare module.exports: any;
}

declare module 'newman/lib/run/options' {
  declare module.exports: any;
}

declare module 'newman/lib/run/summary' {
  declare module.exports: any;
}

declare module 'newman/lib/util' {
  declare module.exports: any;
}

declare module 'newman/lib/version' {
  declare module.exports: any;
}

declare module 'newman/npm/build-docs' {
  declare module.exports: any;
}

declare module 'newman/npm/build-wiki' {
  declare module.exports: any;
}

declare module 'newman/npm/publish-docs' {
  declare module.exports: any;
}

declare module 'newman/npm/publish-wiki' {
  declare module.exports: any;
}

declare module 'newman/npm/test-cli' {
  declare module.exports: any;
}

declare module 'newman/npm/test-integration' {
  declare module.exports: any;
}

declare module 'newman/npm/test-lint' {
  declare module.exports: any;
}

declare module 'newman/npm/test-system' {
  declare module.exports: any;
}

declare module 'newman/npm/test-unit' {
  declare module.exports: any;
}

declare module 'newman/npm/test' {
  declare module.exports: any;
}

declare module 'newman/test/cli/export-environment.test' {
  declare module.exports: any;
}

declare module 'newman/test/cli/export-globals.test' {
  declare module.exports: any;
}

declare module 'newman/test/cli/iteration-count.test' {
  declare module.exports: any;
}

declare module 'newman/test/cli/ssl-client-cert.test' {
  declare module.exports: any;
}

declare module 'newman/test/cli/suppress-exit-code.test' {
  declare module.exports: any;
}

declare module 'newman/test/system/appveyor-yml.test' {
  declare module.exports: any;
}

declare module 'newman/test/system/editorconfig.test' {
  declare module.exports: any;
}

declare module 'newman/test/system/jsdoc-config.test' {
  declare module.exports: any;
}

declare module 'newman/test/system/nsp.test' {
  declare module.exports: any;
}

declare module 'newman/test/system/repository.test' {
  declare module.exports: any;
}

declare module 'newman/test/system/travis-yml.test' {
  declare module.exports: any;
}

declare module 'newman/test/unit/cli-reporter-symbols.test' {
  declare module.exports: any;
}

declare module 'newman/test/unit/cli.test' {
  declare module.exports: any;
}

declare module 'newman/test/unit/run-summary.test' {
  declare module.exports: any;
}

declare module 'newman/test/unit/run.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'newman/bin/newman.js' {
  declare module.exports: $Exports<'newman/bin/newman'>;
}
declare module 'newman/examples/find-unique-urls-in-run.js' {
  declare module.exports: $Exports<'newman/examples/find-unique-urls-in-run'>;
}
declare module 'newman/examples/parallel-collection-runs.js' {
  declare module.exports: $Exports<'newman/examples/parallel-collection-runs'>;
}
declare module 'newman/examples/read-collection-from-file.js' {
  declare module.exports: $Exports<'newman/examples/read-collection-from-file'>;
}
declare module 'newman/examples/run-collections-in-directory.js' {
  declare module.exports: $Exports<'newman/examples/run-collections-in-directory'>;
}
declare module 'newman/index' {
  declare module.exports: $Exports<'newman'>;
}
declare module 'newman/index.js' {
  declare module.exports: $Exports<'newman'>;
}
declare module 'newman/lib/cli/index.js' {
  declare module.exports: $Exports<'newman/lib/cli/index'>;
}
declare module 'newman/lib/config/index.js' {
  declare module.exports: $Exports<'newman/lib/config/index'>;
}
declare module 'newman/lib/config/process-env.js' {
  declare module.exports: $Exports<'newman/lib/config/process-env'>;
}
declare module 'newman/lib/config/rc-file.js' {
  declare module.exports: $Exports<'newman/lib/config/rc-file'>;
}
declare module 'newman/lib/index.js' {
  declare module.exports: $Exports<'newman/lib/index'>;
}
declare module 'newman/lib/node-version-check/index.js' {
  declare module.exports: $Exports<'newman/lib/node-version-check/index'>;
}
declare module 'newman/lib/print/index.js' {
  declare module.exports: $Exports<'newman/lib/print/index'>;
}
declare module 'newman/lib/reporters/cli/cli-utils-symbols.js' {
  declare module.exports: $Exports<'newman/lib/reporters/cli/cli-utils-symbols'>;
}
declare module 'newman/lib/reporters/cli/cli-utils.js' {
  declare module.exports: $Exports<'newman/lib/reporters/cli/cli-utils'>;
}
declare module 'newman/lib/reporters/cli/index.js' {
  declare module.exports: $Exports<'newman/lib/reporters/cli/index'>;
}
declare module 'newman/lib/reporters/emojitrain.js' {
  declare module.exports: $Exports<'newman/lib/reporters/emojitrain'>;
}
declare module 'newman/lib/reporters/html/index.js' {
  declare module.exports: $Exports<'newman/lib/reporters/html/index'>;
}
declare module 'newman/lib/reporters/json/index.js' {
  declare module.exports: $Exports<'newman/lib/reporters/json/index'>;
}
declare module 'newman/lib/reporters/junit/index.js' {
  declare module.exports: $Exports<'newman/lib/reporters/junit/index'>;
}
declare module 'newman/lib/reporters/progress.js' {
  declare module.exports: $Exports<'newman/lib/reporters/progress'>;
}
declare module 'newman/lib/run/export-file.js' {
  declare module.exports: $Exports<'newman/lib/run/export-file'>;
}
declare module 'newman/lib/run/index.js' {
  declare module.exports: $Exports<'newman/lib/run/index'>;
}
declare module 'newman/lib/run/options.js' {
  declare module.exports: $Exports<'newman/lib/run/options'>;
}
declare module 'newman/lib/run/summary.js' {
  declare module.exports: $Exports<'newman/lib/run/summary'>;
}
declare module 'newman/lib/util.js' {
  declare module.exports: $Exports<'newman/lib/util'>;
}
declare module 'newman/lib/version.js' {
  declare module.exports: $Exports<'newman/lib/version'>;
}
declare module 'newman/npm/build-docs.js' {
  declare module.exports: $Exports<'newman/npm/build-docs'>;
}
declare module 'newman/npm/build-wiki.js' {
  declare module.exports: $Exports<'newman/npm/build-wiki'>;
}
declare module 'newman/npm/publish-docs.js' {
  declare module.exports: $Exports<'newman/npm/publish-docs'>;
}
declare module 'newman/npm/publish-wiki.js' {
  declare module.exports: $Exports<'newman/npm/publish-wiki'>;
}
declare module 'newman/npm/test-cli.js' {
  declare module.exports: $Exports<'newman/npm/test-cli'>;
}
declare module 'newman/npm/test-integration.js' {
  declare module.exports: $Exports<'newman/npm/test-integration'>;
}
declare module 'newman/npm/test-lint.js' {
  declare module.exports: $Exports<'newman/npm/test-lint'>;
}
declare module 'newman/npm/test-system.js' {
  declare module.exports: $Exports<'newman/npm/test-system'>;
}
declare module 'newman/npm/test-unit.js' {
  declare module.exports: $Exports<'newman/npm/test-unit'>;
}
declare module 'newman/npm/test.js' {
  declare module.exports: $Exports<'newman/npm/test'>;
}
declare module 'newman/test/cli/export-environment.test.js' {
  declare module.exports: $Exports<'newman/test/cli/export-environment.test'>;
}
declare module 'newman/test/cli/export-globals.test.js' {
  declare module.exports: $Exports<'newman/test/cli/export-globals.test'>;
}
declare module 'newman/test/cli/iteration-count.test.js' {
  declare module.exports: $Exports<'newman/test/cli/iteration-count.test'>;
}
declare module 'newman/test/cli/ssl-client-cert.test.js' {
  declare module.exports: $Exports<'newman/test/cli/ssl-client-cert.test'>;
}
declare module 'newman/test/cli/suppress-exit-code.test.js' {
  declare module.exports: $Exports<'newman/test/cli/suppress-exit-code.test'>;
}
declare module 'newman/test/system/appveyor-yml.test.js' {
  declare module.exports: $Exports<'newman/test/system/appveyor-yml.test'>;
}
declare module 'newman/test/system/editorconfig.test.js' {
  declare module.exports: $Exports<'newman/test/system/editorconfig.test'>;
}
declare module 'newman/test/system/jsdoc-config.test.js' {
  declare module.exports: $Exports<'newman/test/system/jsdoc-config.test'>;
}
declare module 'newman/test/system/nsp.test.js' {
  declare module.exports: $Exports<'newman/test/system/nsp.test'>;
}
declare module 'newman/test/system/repository.test.js' {
  declare module.exports: $Exports<'newman/test/system/repository.test'>;
}
declare module 'newman/test/system/travis-yml.test.js' {
  declare module.exports: $Exports<'newman/test/system/travis-yml.test'>;
}
declare module 'newman/test/unit/cli-reporter-symbols.test.js' {
  declare module.exports: $Exports<'newman/test/unit/cli-reporter-symbols.test'>;
}
declare module 'newman/test/unit/cli.test.js' {
  declare module.exports: $Exports<'newman/test/unit/cli.test'>;
}
declare module 'newman/test/unit/run-summary.test.js' {
  declare module.exports: $Exports<'newman/test/unit/run-summary.test'>;
}
declare module 'newman/test/unit/run.test.js' {
  declare module.exports: $Exports<'newman/test/unit/run.test'>;
}
