FROM ${UPSTREAM_REPO:-testlagoon}/python-3.9:${UPSTREAM_TAG:-latest}
WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8800

RUN pip install flask
COPY . .

ARG LAGOON_GIT_SHA=0000000000000000000000000000000000000000
ENV LAGOON_GIT_SHA_BUILDTIME ${LAGOON_GIT_SHA}

ARG LAGOON_GIT_BRANCH=undefined
ENV LAGOON_GIT_BRANCH_BUILDTIME ${LAGOON_GIT_BRANCH}

ARG LAGOON_BUILD_TYPE=undefined
ENV LAGOON_BUILD_TYPE_BUILDTIME ${LAGOON_BUILD_TYPE}

ARG LAGOON_PR_HEAD_BRANCH=undefined
ENV LAGOON_PR_HEAD_BRANCH_BUILDTIME ${LAGOON_PR_HEAD_BRANCH}

ARG LAGOON_PR_HEAD_SHA=undefined
ENV LAGOON_PR_HEAD_SHA_BUILDTIME ${LAGOON_PR_HEAD_SHA}

ARG LAGOON_PR_BASE_BRANCH=undefined
ENV LAGOON_PR_BASE_BRANCH_BUILDTIME ${LAGOON_PR_BASE_BRANCH}

ARG LAGOON_PR_BASE_SHA=undefined
ENV LAGOON_PR_BASE_SHA_BUILDTIME ${LAGOON_PR_BASE_SHA}

ARG LAGOON_PR_TITLE=undefined
ENV LAGOON_PR_TITLE_BUILDTIME ${LAGOON_PR_TITLE}

CMD ["flask", "run"]