// flow-typed signature: 2fa1bf3f484943a1d0f8c19ab090255b
// flow-typed version: <<STUB>>/bl_v~1.1.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bl/bl' {
  declare module.exports: any;
}

declare module 'bl/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bl/bl.js' {
  declare module.exports: $Exports<'bl/bl'>;
}
declare module 'bl/test/test.js' {
  declare module.exports: $Exports<'bl/test/test'>;
}
