mutation addEnvVariable {
  addEnvVariable: addEnvVariable(
    input:{
      type: {{ envType }},
      typeId: {{ project_id }},
      scope: {{ envScope }},
      name: "{{ envName }}",
      value: "{{ envValue }}"
    }
  ) {
    id,
    name,
    value,
    scope
  }
}