mutation addProject {
  CiAddProject: addProject(
    input: {
      name: "{{ project }}"
      openshift: 2001
      organization: 2
      gitUrl: "{{ git_http_url }}"
      productionEnvironment: "{{ prodenv }}"
      standbyProductionEnvironment: "{{ standbyenv }}"
      subfolder: "{{ subfolder }}"
      privateKey: "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\nQyNTUxOQAAACAka6joPD9jPHpzSh9Ef2G2leBHb4dT9tWEujqbODItuQAAAJiCjhW5go4V\nuQAAAAtzc2gtZWQyNTUxOQAAACAka6joPD9jPHpzSh9Ef2G2leBHb4dT9tWEujqbODItuQ\nAAAEC37LKYUcj38A/7MMiL1ncqcWKCtfnrDYGzdJJx4ak0ciRrqOg8P2M8enNKH0R/YbaV\n4Edvh1P21YS6Ops4Mi25AAAAEWJlbkBzaHJlZGRlZGJhY29uAQIDBA==\n-----END OPENSSH PRIVATE KEY-----"
    }
  ) {
    id
  }

  CiAddGroup: addGroup(
    input: {
      name: "ci-org-group"
    }
  ) {
    id
  }

  CiAddGroupToOrg: addExistingGroupToOrganization(
    input: {
      name: "ci-org-group"
      organization: 2
    }
  ) {
    id
  }

  CiAddGroupToProject: addGroupsToProject(
    input: {
      project: {
        name: "{{ project }}"
      }
      groups: [
        {
          name: "ci-org-group"
        }
      ]
    }
  ) {
    id
  }

  CiAddRocketChat: addNotificationToProject(
    input: {
      project: "{{ project }}"
      notificationType: SLACK
      notificationName: "org-slack-test"
    }
  ) {
    id
  }

  CiAddEmail: addNotificationToProject(
    input: {
      project: "{{ project }}"
      notificationType: EMAIL
      notificationName: "org-email-test"
    }
  ) {
    id
  }
}