mutation addOrUpdateEnvironment {
  addOrUpdateEnvironment: addOrUpdateEnvironment(
    input: {
      name: "{{ name }}"
      project: {{ project_id }}
      deployType: {{ deployType }}
      deployBaseRef: "{{ deployBaseRef }}"
      environmentType: {{ environmentType }}
    }
  ) {
    id,
    name
  }
}