mutation addEnvVariable {
  addOrUpdateEnvVariableByName(
    input: {
      project: "{{ project }}"
      environment: "{{ branch }}"
      scope: {{ envScope }},
      name: "{{ envName }}",
      value: "{{ envValue }}"
    }
  ) {
    id
    scope
    name
    value
  }
}