mutation batchAddEnvVariables {
  addOrUpdateEnvVariablesByName(
    input: {
      project: "{{ project }}"
      variables: [
{% for v in variables %}
        { name: {{ v.name | to_json }}, value: {{ v.value | to_json }}, scope: {{ v.scope }} }{% if not loop.last %},{% endif %}
{% endfor %}
      ]
    }
  ) {
    successCount
    failureCount
    results {
      name
      success
      error
      envVariable {
        id
        scope
        name
        value
      }
    }
  }
}
