query getEnvVariablesByProjectEnvironmentName {
  getEnvVariablesByProjectEnvironmentName(
    input: {
      project: "{{ project }}"
      environment: "{{ branch }}"
    }
  ) {
    name
    value
  }
}
