mutation deployEnvironmentPromote {
  deployEnvironmentPromote(
    input:{
      destinationEnvironment:"{{ promote_environment }}",
      project:{
        name:"{{ project }}"
      },
      sourceEnvironment:{
        name:"{{ source_environment }}",
        project:{
          name:"{{ project }}"
        }
      },
      returnData: true
    }
  )
}