package lagoon

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/uselagoon/machinery/api/schema"
)

var (
	apiRoutesFragment = `
		domain
		service
		alternativeNames{
			domain
		}
		annotations{
			key
			value
		}
		pathRoutes{
			toService
			path
		}
		tlsAcme
		insecure
		hstsEnabled
		hstsIncludeSubdomains
		hstsPreload
		hstsMaxAge
		primary
		source
		type
	`
	agRoutesFragment = `
		updated
		enabled
		allowPullRequests
		prefixes
		tlsAcme
		insecure
		pathRoutes {
			toService
			fromService
			path
		}
		disableRequestVerification
	`
	deploytargetFragment = `
		id
		name
		routerPattern
		buildImage
		disabled
		sharedBaasBucketName
		monitoringConfig
	`
)

func (l *LagoonAPI) addOrUpdateEnvironment(deployData DeployData, deployBaseRef, deployHeadRef, deployTitle, environmentType string) (*schema.Environment, error) {
	lc, _ := GetClient(*l)
	envMutation := fmt.Sprintf(`mutation addOrUpdateEnvironment($name: String!, $project: Int!, $openshift: Int, $deployType: DeployType!, $deployBaseRef: String!,
	$deployHeadRef: String, $deployTitle: String, $environmentType: EnvType!) {
		addOrUpdateEnvironment(input:{
			name: $name,
			project: $project,
			openshift: $openshift,
			deployType: $deployType,
			deployBaseRef: $deployBaseRef,
			deployHeadRef: $deployHeadRef,
			deployTitle: $deployTitle,
			environmentType: $environmentType,
		}) {
			id
			name
			project {
				name
			}
			autoIdle
			deployType
			environmentType
			openshiftProjectName
			envVariables {
				name
				value
				scope
			}
			apiRoutes(source: API) {
				%s
			}
			autogeneratedRouteConfig {
				%s
			}
		}
	}`, apiRoutesFragment, agRoutesFragment)
	addOrUpdateEnvironment, err := lc.ProcessRaw(context.Background(), envMutation, map[string]interface{}{
		"name":            deployData.UnsafeEnvironmentName,
		"project":         deployData.Project.ID,
		"deployType":      deployData.DeployType,
		"deployBaseRef":   deployBaseRef,
		"environmentType": environmentType,
		"openshift":       deployData.DeployTarget.ID,
		"deployHeadRef":   deployHeadRef,
		"deployTitle":     deployTitle,
	})
	if err != nil {
		return nil, err
	}
	// d, _ := json.Marshal(addOrUpdateEnvironment)
	// fmt.Println(string(d))
	aoue := schema.Environment{}
	ab, _ := json.Marshal(addOrUpdateEnvironment.(map[string]interface{})["addOrUpdateEnvironment"])
	json.Unmarshal(ab, &aoue)
	return &aoue, nil
}

type Deployment struct {
	schema.Deployment
	BuildType DeploymentBuildType `json:"buildType,omitempty"`
}

func (l *LagoonAPI) addDeployment(deployData DeployData, environmentID, buildPriority uint) (*Deployment, error) {
	lc, _ := GetClient(*l)
	deployMutation := `mutation addDeployment($name: String!, $status: DeploymentStatusType!, $created: String!, $environment: Int!, $id: Int,
	$priority: Int, $bulkId: String, $bulkName: String,
    $sourceUser: String, $sourceType: DeploymentSourceType, $buildType: DeploymentBuildType) {
		addDeployment(input: {
			name: $name
			status: $status
			created: $created
			environment: $environment
			id: $id
			priority: $priority
			bulkId: $bulkId
			bulkName: $bulkName
			sourceUser: $sourceUser
			sourceType: $sourceType
			buildType: $buildType
		}) {
			id
			name
			status
			created
			started
			completed
			remoteId
			uiLink
			environment {
				name
			}
			buildType
		}
  	}`
	d, err := lc.ProcessRaw(context.Background(), deployMutation, map[string]interface{}{
		"name":        deployData.BuildName,
		"status":      "NEW",
		"created":     time.Now().UTC().Format("2006-01-02T15:04:05"),
		"environment": environmentID,
		"priority":    buildPriority,
		"bulkId":      deployData.BulkID,
		"bulkName":    deployData.BulkName,
		"sourceUser":  deployData.SourceUser,
		"sourceType":  deployData.SourceType,
		"buildType":   deployData.BuildType,
	})
	if err != nil {
		return nil, err
	}
	// da, _ := json.Marshal(d)
	// fmt.Println(string(da))
	deployment := Deployment{}
	db, _ := json.Marshal(d.(map[string]interface{})["addDeployment"])
	json.Unmarshal(db, &deployment)
	return &deployment, nil
}

func (l *LagoonAPI) AllProjectByGitURL(gitURL string) (*[]schema.Project, error) {
	lc, _ := GetClient(*l)
	query := fmt.Sprintf(`query allProjects($gitUrl: String) {
        allProjects(gitUrl: $gitUrl) {
			id
        	name
        	deploymentsDisabled
			developmentBuildPriority
			productionBuildPriority
			routerPattern
			sharedBaasBucket
			privateKey
			autoIdle
			storageCalc
			gitUrl
			subfolder
			branches
			pullrequests
			buildImage
			envVariables {
				name
				value
				scope
			}
			openshift {
				%s
			}
			developmentEnvironmentsLimit
			productionEnvironment
			standbyProductionEnvironment
			environments(includeDeleted:false) {
				name
				id
				environmentType
				autoIdle
				kubernetesNamespaceName
				openshift {
					%s
				}
				apiRoutes(source: API) {
					%s
				}
				autogeneratedRouteConfig {
					%s
				}
			}
			apiRoutes {
				%s
			}
			autogeneratedRouteConfig {
				%s
			}
			deployTargetConfigs {
			    id
				weight
				branches
				pullrequests
				weight
				deployTarget {
					%s
				}
			}
        	organizationDetails {
				id
				name
				friendlyName
				description
				quotaProject
				quotaGroup
				quotaNotification
				quotaEnvironment
				quotaRoute
				envVariables {
					name
					value
					scope
				}
				environments {
					name
					id
					environmentType
					autoIdle
					kubernetesNamespaceName
					openshift {
						%s
					}
				}
			}
        }
    }`, deploytargetFragment, deploytargetFragment, apiRoutesFragment, agRoutesFragment, apiRoutesFragment, agRoutesFragment, deploytargetFragment, deploytargetFragment)
	result, err := lc.ProcessRaw(context.Background(), query, map[string]interface{}{
		"gitUrl": gitURL,
	})
	if err != nil {
		return nil, err
	}
	// d, _ := json.Marshal(result)
	// fmt.Println(string(d))
	rb, _ := json.Marshal(result.(map[string]interface{})["allProjects"])
	projects := []schema.Project{}
	json.Unmarshal(rb, &projects)
	return &projects, nil
}

func (l *LagoonAPI) ProjectByName(name string) (*schema.Project, error) {
	lc, _ := GetClient(*l)
	query := fmt.Sprintf(`query projectByName($name: String!) {
        projectByName(name: $name) {
			id
        	name
        	deploymentsDisabled
			developmentBuildPriority
			productionBuildPriority
			routerPattern
			sharedBaasBucket
			privateKey
			autoIdle
			storageCalc
			gitUrl
			subfolder
			branches
			pullrequests
			buildImage
			envVariables {
				name
				value
				scope
			}
			openshift {
				%s
			}
			developmentEnvironmentsLimit
			productionEnvironment
			standbyProductionEnvironment
			environments(includeDeleted:false) {
				name
				id
				environmentType
				autoIdle
				kubernetesNamespaceName
				openshift {
					%s
				}
				apiRoutes(source: API) {
					%s
				}
				autogeneratedRouteConfig {
					%s
				}
			}
			apiRoutes {
				%s
			}
			autogeneratedRouteConfig {
				%s
			}
			deployTargetConfigs {
			    id
				weight
				branches
				pullrequests
				weight
				deployTarget {
					%s
				}
			}
        	organizationDetails {
				id
				name
				friendlyName
				description
				quotaProject
				quotaGroup
				quotaNotification
				quotaEnvironment
				quotaRoute
				envVariables {
					name
					value
					scope
				}
				environments {
					name
					id
					environmentType
					autoIdle
					kubernetesNamespaceName
					openshift {
						%s
					}
				}
			}
        }
    }`, deploytargetFragment, deploytargetFragment, apiRoutesFragment, agRoutesFragment, apiRoutesFragment, agRoutesFragment, deploytargetFragment, deploytargetFragment)
	result, err := lc.ProcessRaw(context.Background(), query, map[string]interface{}{
		"name": name,
	})
	if err != nil {
		return nil, err
	}
	// r, _ := json.Marshal(result)
	// fmt.Println(string(r))
	rb, _ := json.Marshal(result.(map[string]interface{})["projectByName"])
	project := schema.Project{}
	json.Unmarshal(rb, &project)
	return &project, nil
}

func (l *LagoonAPI) EnvironmentByID(id int) (*schema.Environment, error) {
	lc, _ := GetClient(*l)
	query := fmt.Sprintf(`query environmentById($id: Int!) {
        environmentById(id: $id) {
		    id
			name
			autoIdle
			deployType
			environmentType
			openshiftProjectName
			openshift {
				%s
			}
			envVariables {
				name
				value
				scope
			}
			apiRoutes {
				%s
			}
			autogeneratedRouteConfig {
				%s
			}
        }
    }`, deploytargetFragment, apiRoutesFragment, agRoutesFragment)
	result, err := lc.ProcessRaw(context.Background(), query, map[string]interface{}{
		"id": id,
	})
	if err != nil {
		return nil, err
	}
	// r, _ := json.Marshal(result)
	// fmt.Println(string(r))
	rb, _ := json.Marshal(result.(map[string]interface{})["environmentById"])
	environment := schema.Environment{}
	json.Unmarshal(rb, &environment)
	return &environment, nil
}
