{{- range $cronjobName, $cronjobConfig := .Values.nativeCronjobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-{{ $.Release.Name }}-{{ $cronjobName }}
  labels:
    {{- include "mongodb-single.labels" $ | nindent 4 }}
  annotations:
    {{- include "mongodb-single.annotations" $ | nindent 4 }}
spec:
  schedule: {{ $cronjobConfig.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 240
  jobTemplate:
    metadata:
      labels:
        {{- include "mongodb-single.labels" $ | nindent 8 }}
      annotations:
        {{- include "mongodb-single.annotations" $ | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            {{- include "mongodb-single.labels" $ | nindent 12 }}
          annotations:
            {{- include "mongodb-single.annotations" $ | nindent 12 }}
        spec:
        {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          priorityClassName: {{ include "mongodb-single.lagoonPriority" $ }}
          enableServiceLinks: false
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          volumes:
            - name: {{ include "mongodb-single.fullname" $ }}
              persistentVolumeClaim:
                claimName: {{ include "mongodb-single.fullname" $ }}
          containers:
            - image: {{ $.Values.image | quote }}
              name: cronjob-{{ $.Release.Name }}-{{ $cronjobName }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              imagePullPolicy: {{ $.Values.imagePullPolicy }}
              command:
                - /lagoon/cronjob.sh
                - {{ $cronjobConfig.command }}
              env:
                - name: LAGOON_GIT_SHA
                  value: {{ $.Values.gitSha | quote }}
                - name: SERVICE_NAME
                  value: {{ $.Release.Name | quote }}
              envFrom:
                - configMapRef:
                    name: lagoon-env
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              volumeMounts:
                - name: {{ include "mongodb-single.fullname" $ }}
                  mountPath: {{ $.Values.persistentStorage.path | quote }}
          restartPolicy: Never
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml $ | nindent 12 }}
          {{- end }}
        {{- with $.Values.affinity }}
          affinity:
            {{- toYaml $ | nindent 12 }}
        {{- end }}
        {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml $ | nindent 12 }}
        {{- end }}
{{- end }}
