ARG UPSTREAM_REPO
FROM ${UPSTREAM_REPO:-uselagoon}/mariadb

ENV MARIADB_DATABASE=keycloak \
    MARIADB_USER=keycloak \
    MARIADB_PASSWORD=keycloak \
    MARIADB_CHARSET=utf8 \
    MARIADB_COLLATION=utf8_general_ci
