package lagoonclient

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// __getEnvironmentWorkflowsInput is used internally by genqlient
type __getEnvironmentWorkflowsInput struct {
	Project int    `json:"project"`
	Name    string `json:"name"`
}

// getEnvironmentWorkflowsEnvironmentByNameEnvironment includes the requested fields of the GraphQL type Environment.
// The GraphQL type's documentation follows.
//
// Lagoon Environment (for each branch, pullrequest there is an individual environment)
type getEnvironmentWorkflowsEnvironmentByNameEnvironment struct {
	// Internal ID of this Environment
	Id int `json:"id"`
	// Name of this Environment
	Name      string                                                                 `json:"name"`
	Workflows []getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow `json:"workflows"`
}

// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow includes the requested fields of the GraphQL type Workflow.
type getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow struct {
	Id                     int                                                                                        `json:"id"`
	Event                  string                                                                                     `json:"event"`
	AdvancedTaskDefinition getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition `json:"-"`
}

func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow
		AdvancedTaskDefinition json.RawMessage `json:"advancedTaskDefinition"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.AdvancedTaskDefinition
		src := firstPass.AdvancedTaskDefinition
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"Unable to unmarshal getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow.AdvancedTaskDefinition: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow struct {
	Id int `json:"id"`

	Event string `json:"event"`

	AdvancedTaskDefinition json.RawMessage `json:"advancedTaskDefinition"`
}

func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow) __premarshalJSON() (*__premarshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow, error) {
	var retval __premarshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow

	retval.Id = v.Id
	retval.Event = v.Event
	{

		dst := &retval.AdvancedTaskDefinition
		src := v.AdvancedTaskDefinition
		var err error
		*dst, err = __marshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"Unable to marshal getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflow.AdvancedTaskDefinition: %w", err)
		}
	}
	return &retval, nil
}

// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition includes the requested fields of the GraphQL interface AdvancedTaskDefinition.
//
// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition is implemented by the following types:
// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage
// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand
type getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition interface {
	implementsGraphQLInterfacegetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage) implementsGraphQLInterfacegetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition() {
}

// GetTypename is a part of, and documented with, the interface getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition.
func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage) GetTypename() string {
	return v.Typename
}

func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand) implementsGraphQLInterfacegetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition() {
}

// GetTypename is a part of, and documented with, the interface getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition.
func (v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand) GetTypename() string {
	return v.Typename
}

func __unmarshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition(b []byte, v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "AdvancedTaskDefinitionImage":
		*v = new(getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage)
		return json.Unmarshal(b, *v)
	case "AdvancedTaskDefinitionCommand":
		*v = new(getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"Response was missing AdvancedTaskDefinition.__typename")
	default:
		return fmt.Errorf(
			`Unexpected concrete type for getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition: "%v"`, tn.TypeName)
	}
}

func __marshalgetEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition(v *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage:
		typename = "AdvancedTaskDefinitionImage"

		result := struct {
			TypeName string `json:"__typename"`
			*getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage
		}{typename, v}
		return json.Marshal(result)
	case *getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand:
		typename = "AdvancedTaskDefinitionCommand"

		result := struct {
			TypeName string `json:"__typename"`
			*getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`Unexpected concrete type for getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinition: "%T"`, v)
	}
}

// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand includes the requested fields of the GraphQL type AdvancedTaskDefinitionCommand.
type getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionCommand struct {
	Typename string `json:"__typename"`
	Id       int    `json:"id"`
	Command  string `json:"command"`
}

// getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage includes the requested fields of the GraphQL type AdvancedTaskDefinitionImage.
type getEnvironmentWorkflowsEnvironmentByNameEnvironmentWorkflowsWorkflowAdvancedTaskDefinitionAdvancedTaskDefinitionImage struct {
	Typename string `json:"__typename"`
	Id       int    `json:"id"`
	Image    string `json:"image"`
}

// getEnvironmentWorkflowsResponse is returned by getEnvironmentWorkflows on success.
type getEnvironmentWorkflowsResponse struct {
	EnvironmentByName getEnvironmentWorkflowsEnvironmentByNameEnvironment `json:"environmentByName"`
}

func getEnvironmentWorkflows(
	ctx context.Context,
	client graphql.Client,
	project int,
	name string,
) (*getEnvironmentWorkflowsResponse, error) {
	__input := __getEnvironmentWorkflowsInput{
		Project: project,
		Name:    name,
	}
	var err error

	var retval getEnvironmentWorkflowsResponse
	err = client.MakeRequest(
		ctx,
		"getEnvironmentWorkflows",
		`
query getEnvironmentWorkflows ($project: Int!, $name: String!) {
	environmentByName(project: $project, name: $name) {
		id
		name
		workflows {
			id
			event
			advancedTaskDefinition {
				__typename
				... on AdvancedTaskDefinitionCommand {
					id
					command
				}
				... on AdvancedTaskDefinitionImage {
					id
					image
				}
			}
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}
