apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-schedule
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: ARCHIVE_SCHEDULE
    description: Schedule of the Archive Runs in Cron format
    required: true
  - name: ARCHIVE_BUCKET
    description: S3 bucket of the Archive
    required: true
objects:
- apiVersion: backup.appuio.ch/v1alpha1
  kind: Schedule
  metadata:
    name: archive-schedule
    labels:
      schedule: archive
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
  spec:
    archive:
      restoreMethod:
        s3:
          bucket: '${ARCHIVE_BUCKET}'
      schedule: '${ARCHIVE_SCHEDULE}'
    backend:
      repoPasswordSecretRef:
        key: repo-pw
        name: baas-repo-pw
      s3:
        bucket: 'baas-${SAFE_PROJECT}'
