apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-schedule
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: BACKUP_SCHEDULE
    description: Schedule of the Backup in Cron format or auto schedule format
    required: true
  - name: CHECK_SCHEDULE
    description: Schedule of the Backup Check in Cron format or auto schedule format
    required: true
  - name: PRUNE_SCHEDULE
    description: Schedule of the Backup Prune in Cron format or auto schedule format
    required: true
  - name: BAAS_BUCKET_NAME
    description: Which bucket the backups for this project should go to
    required: true
  - name: MONTHLY_BACKUP_RETENTION
    description: How many monthly backups should be retained after pruning
    required: true
  - name: WEEKLY_BACKUP_RETENTION
    description: How many weekly backups should be retained after pruning
    required: true
  - name: DAILY_BACKUP_RETENTION
    description: How many daily backups should be retained after pruning
    required: true
  - name: LAGOON_ENVIRONMENT_TYPE
    description: What type of environment this is (production/development)
    required: true
objects:
- apiVersion: backup.appuio.ch/v1alpha1
  kind: Schedule
  metadata:
    name: backup-schedule
    labels:
      schedule: backup
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
  spec:
    backend:
      repoPasswordSecretRef:
        key: repo-pw
        name: baas-repo-pw
      s3:
        bucket: '${BAAS_BUCKET_NAME}'
    backup:
      schedule: '${BACKUP_SCHEDULE}'
    check:
      schedule: '${CHECK_SCHEDULE}'
    prune:
      retention:
        keepDaily: ${DAILY_BACKUP_RETENTION}
        keepWeekly: ${WEEKLY_BACKUP_RETENTION}
        keepMonthly: ${MONTHLY_BACKUP_RETENTION}
      schedule: '${PRUNE_SCHEDULE}'
