apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-fluentd
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      service: ${SERVICE_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
      spec:
        containers:
        - image: ${REGISTRY}/${OPENSHIFT_PROJECT}/${SERVICE_NAME}:latest
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 24224
            protocol: TCP
          readinessProbe:
            tcp:
              port: 9600
            initialDelaySeconds: 20
          livenessProbe:
            tcp:
              port: 9600
            initialDelaySeconds: 120
          envFrom:
          - configMapRef:
              name: lagoon-env
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
        volumes:
        - name: volume-4750i
          secret:
            defaultMode: 420
            items:
            - key: FORWARD_KEY
              path: ca_key.pem
            - key: FORWARD_CERTIFICATE
              path: ca_cert.pem
            secretName: collector
        - configMap:
            defaultMode: 420
            items:
            - key: FLUENT_CONF
              path: fliuentd.conf
            name: lagoon-env
          name: volume-g7qqi
      terminationGracePeriodSeconds: 30
    volumeMounts:
    - mountPath: /fluentd/ssl/
      name: volume-4750i
      readOnly: true
    - mountPath: /fluentd/etc/
      name: volume-g7qqi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: secure_forward
      port: 24224
      protocol: TCP
      targetPort: 24224
    selector:
      service: ${SERVICE_NAME}
  status:
    loadBalancer: {}
