apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template
parameters:
  - name: TAG
    description: Which docker image tag should be deployed
    required: true
  - name: NAME
    description: Name of the objects to create
    required: true
  - name: SHORT_NAME
    description: Shorter name of the objects to create, can be max 24 chars
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to
    required: true
  - name: ROUTER_URL
    description: URL of the Router
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: ' '
          name: node
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 9600
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 120
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - node
        from:
          kind: ImageStreamTag
          name: ${SITEGROUP}:${TAG}
      type: ImageChange
  status: {}