#!/bin/sh

# Inject Matomo tracking snippets via nginx configuration.

# Single site configuration.
if [ "$MATOMO_URL" ]; then

    # Add Matomo tracking code to end of the HEAD section.
    cat <<EOF >> /etc/nginx/conf.d/matomo.conf
sub_filter '</head>'
"<!-- Matomo -->
<script type='text/javascript'>
var _paq = window._paq = window._paq || [];
/* tracker methods like 'setCustomDimension' should be called before 'trackPageView' */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
    var u='${MATOMO_URL}';
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '${MATOMO_SITE_ID:-1}']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
</script>
<!-- End Matomo Code -->
</head>";
sub_filter_once on;
EOF

fi

# Tag manager configuration.
if [ "$MATOMO_TAG_MANAGER_URL" ]; then

    cat <<EOF >> /etc/nginx/conf.d/matomo.conf
sub_filter '<head>'
"<head>
<!-- Matomo Tag Manager -->
<script type='text/javascript'>
var _mtm = window._mtm = window._mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.src='${MATOMO_TAG_MANAGER_URL}'; s.parentNode.insertBefore(g,s);
</script>
<!-- End Matomo Tag Manager -->";
sub_filter_once on;
EOF

fi
