docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: drush updb
        command: drush updb --cache-clear=0
        service: cli
    - run:
        name: drush cc all
        command: drush cc all
        service: cli

environments:
  main:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *" # this will run the cron once per Hour
        command: drush cron
        service: cli
