ARG UPSTREAM_REPO
ARG UPSTREAM_TAG
FROM ${UPSTREAM_REPO:-testlagoon}/node-16-builder:${UPSTREAM_TAG:-latest} as builder
COPY package.json yarn.lock /app/
RUN yarn install

FROM ${UPSTREAM_REPO:-testlagoon}/node-16:${UPSTREAM_TAG:-latest}
COPY --from=builder /app/node_modules /app/node_modules
COPY . /app/

ARG LAGOON_GIT_SHA=0000000000000000000000000000000000000000
ENV LAGOON_GIT_SHA_BUILDTIME ${LAGOON_GIT_SHA}

ARG LAGOON_GIT_BRANCH=undefined
ENV LAGOON_GIT_BRANCH_BUILDTIME ${LAGOON_GIT_BRANCH}

ARG LAGOON_API_VARIABLE_PROJECT
ENV LAGOON_API_VARIABLE_PROJECT_BUILDTIME ${LAGOON_API_VARIABLE_PROJECT}

ARG LAGOON_API_VARIABLE_MULTILINE_SPACED
ENV LAGOON_API_VARIABLE_MULTILINE_SPACED_BUILDTIME ${LAGOON_API_VARIABLE_MULTILINE_SPACED}

ARG LAGOON_API_VARIABLE_ENVIRONMENT
ENV LAGOON_API_VARIABLE_ENVIRONMENT_BUILDTIME ${LAGOON_API_VARIABLE_ENVIRONMENT}

ARG LAGOON_API_VARIABLE_OVERRIDE
ENV LAGOON_API_VARIABLE_OVERRIDE_BUILDTIME ${LAGOON_API_VARIABLE_OVERRIDE}

ARG LAGOON_API_VARIABLE_BUILD
ENV LAGOON_API_VARIABLE_BUILD_BUILDTIME ${LAGOON_API_VARIABLE_BUILD}

ARG LAGOON_API_VARIABLE_RUNTIME
ENV LAGOON_API_VARIABLE_RUNTIME_BUILDTIME ${LAGOON_API_VARIABLE_RUNTIME}

EXPOSE 3000

CMD ["yarn", "run", "start"]
