#!/bin/bash

# takes arguments:
# 1: name of oc project
# 2(optional): override for deploymentconfig


if [[ "$1" =~ ^[A-Za-z0-9]+$ ]]; then
  project=$1
else
  exit
fi

if [[ "$2" =~ ^[A-Za-z0-9]+$ ]]; then
  deployment=$2
else
  deployment=cli
fi

TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
/usr/bin/oc login --insecure-skip-tls-verify --token="${TOKEN}" https://kubernetes.default.svc
/usr/bin/oc -n ${project} rsh dc/${deployment}
