#!/bin/bash

# takes arguments:
# 1: name of oc projects


if [[ "$1" =~ ^[A-Za-z0-9]+$ ]]; then
  project=$1
else
  exit
fi

if [[ "$2" =~ ^[A-Za-z0-9]+$ ]]; then
  deployment=$2
else
  deployment=cli
fi

/usr/bin/oc -n ${project} rsh dc/${deployment}
