// flow-typed signature: 64f7952d42fba50a5014f03d0a999d2d
// flow-typed version: <<STUB>>/fetch-everywhere_v^1.0.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-everywhere'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-everywhere' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-everywhere/fetch-bower' {
  declare module.exports: any;
}

declare module 'fetch-everywhere/fetch-npm-browserify' {
  declare module.exports: any;
}

declare module 'fetch-everywhere/fetch-npm-node' {
  declare module.exports: any;
}

declare module 'fetch-everywhere/test/api.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-everywhere/fetch-bower.js' {
  declare module.exports: $Exports<'fetch-everywhere/fetch-bower'>;
}
declare module 'fetch-everywhere/fetch-npm-browserify.js' {
  declare module.exports: $Exports<'fetch-everywhere/fetch-npm-browserify'>;
}
declare module 'fetch-everywhere/fetch-npm-node.js' {
  declare module.exports: $Exports<'fetch-everywhere/fetch-npm-node'>;
}
declare module 'fetch-everywhere/test/api.test.js' {
  declare module.exports: $Exports<'fetch-everywhere/test/api.test'>;
}
