// flow-typed signature: c3dc3c760030efdc83aaa1d4ba112b50
// flow-typed version: <<STUB>>/jssha_v^2.2.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jssha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jssha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jssha/src/sha' {
  declare module.exports: any;
}

declare module 'jssha/src/sha1' {
  declare module.exports: any;
}

declare module 'jssha/src/sha256' {
  declare module.exports: any;
}

declare module 'jssha/src/sha3' {
  declare module.exports: any;
}

declare module 'jssha/src/sha512' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jssha/src/sha.js' {
  declare module.exports: $Exports<'jssha/src/sha'>;
}
declare module 'jssha/src/sha1.js' {
  declare module.exports: $Exports<'jssha/src/sha1'>;
}
declare module 'jssha/src/sha256.js' {
  declare module.exports: $Exports<'jssha/src/sha256'>;
}
declare module 'jssha/src/sha3.js' {
  declare module.exports: $Exports<'jssha/src/sha3'>;
}
declare module 'jssha/src/sha512.js' {
  declare module.exports: $Exports<'jssha/src/sha512'>;
}
