// flow-typed signature: 05dd1f598eeb9aae46b72ab68adba2dc
// flow-typed version: <<STUB>>/styled-normalize_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-normalize/dist/index' {
  declare module.exports: any;
}

declare module 'styled-normalize/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-normalize/dist/index.js' {
  declare module.exports: $Exports<'styled-normalize/dist/index'>;
}
declare module 'styled-normalize/src/index.js' {
  declare module.exports: $Exports<'styled-normalize/src/index'>;
}
