// flow-typed signature: de1899d25f5351f8feed25bd9da7a8c1
// flow-typed version: <<STUB>>/sync-request_v^4.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sync-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sync-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sync-request/browser' {
  declare module.exports: any;
}

declare module 'sync-request/lib/find-port' {
  declare module.exports: any;
}

declare module 'sync-request/lib/json-buffer/index' {
  declare module.exports: any;
}

declare module 'sync-request/lib/legacy-worker' {
  declare module.exports: any;
}

declare module 'sync-request/lib/nc-server' {
  declare module.exports: any;
}

declare module 'sync-request/test/benchmark-server' {
  declare module.exports: any;
}

declare module 'sync-request/test/benchmark' {
  declare module.exports: any;
}

declare module 'sync-request/test/empty' {
  declare module.exports: any;
}

declare module 'sync-request/test/external-test' {
  declare module.exports: any;
}

declare module 'sync-request/test/fake-server' {
  declare module.exports: any;
}

declare module 'sync-request/test/index' {
  declare module.exports: any;
}

declare module 'sync-request/test/internal-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sync-request/browser.js' {
  declare module.exports: $Exports<'sync-request/browser'>;
}
declare module 'sync-request/index' {
  declare module.exports: $Exports<'sync-request'>;
}
declare module 'sync-request/index.js' {
  declare module.exports: $Exports<'sync-request'>;
}
declare module 'sync-request/lib/find-port.js' {
  declare module.exports: $Exports<'sync-request/lib/find-port'>;
}
declare module 'sync-request/lib/json-buffer/index.js' {
  declare module.exports: $Exports<'sync-request/lib/json-buffer/index'>;
}
declare module 'sync-request/lib/legacy-worker.js' {
  declare module.exports: $Exports<'sync-request/lib/legacy-worker'>;
}
declare module 'sync-request/lib/nc-server.js' {
  declare module.exports: $Exports<'sync-request/lib/nc-server'>;
}
declare module 'sync-request/test/benchmark-server.js' {
  declare module.exports: $Exports<'sync-request/test/benchmark-server'>;
}
declare module 'sync-request/test/benchmark.js' {
  declare module.exports: $Exports<'sync-request/test/benchmark'>;
}
declare module 'sync-request/test/empty.js' {
  declare module.exports: $Exports<'sync-request/test/empty'>;
}
declare module 'sync-request/test/external-test.js' {
  declare module.exports: $Exports<'sync-request/test/external-test'>;
}
declare module 'sync-request/test/fake-server.js' {
  declare module.exports: $Exports<'sync-request/test/fake-server'>;
}
declare module 'sync-request/test/index.js' {
  declare module.exports: $Exports<'sync-request/test/index'>;
}
declare module 'sync-request/test/internal-test.js' {
  declare module.exports: $Exports<'sync-request/test/internal-test'>;
}
