// flow-typed signature: 59e49812c44fc8e0d9fb78e6a1f0972b
// flow-typed version: <<STUB>>/winston_v^2.3.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston/lib/winston' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/common' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config/cli-config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config/npm-config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/config/syslog-config' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/container' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/exception' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/logger' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/console' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/file' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/http' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/memory' {
  declare module.exports: any;
}

declare module 'winston/lib/winston/transports/transport' {
  declare module.exports: any;
}

declare module 'winston/test/helpers' {
  declare module.exports: any;
}

declare module 'winston/test/transports/console-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-archive-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-maxfiles-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-maxsize-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-open-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-stress-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-tailrolling-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/file-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/http-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/memory-test' {
  declare module.exports: any;
}

declare module 'winston/test/transports/transport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston/lib/winston.js' {
  declare module.exports: $Exports<'winston/lib/winston'>;
}
declare module 'winston/lib/winston/common.js' {
  declare module.exports: $Exports<'winston/lib/winston/common'>;
}
declare module 'winston/lib/winston/config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config'>;
}
declare module 'winston/lib/winston/config/cli-config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config/cli-config'>;
}
declare module 'winston/lib/winston/config/npm-config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config/npm-config'>;
}
declare module 'winston/lib/winston/config/syslog-config.js' {
  declare module.exports: $Exports<'winston/lib/winston/config/syslog-config'>;
}
declare module 'winston/lib/winston/container.js' {
  declare module.exports: $Exports<'winston/lib/winston/container'>;
}
declare module 'winston/lib/winston/exception.js' {
  declare module.exports: $Exports<'winston/lib/winston/exception'>;
}
declare module 'winston/lib/winston/logger.js' {
  declare module.exports: $Exports<'winston/lib/winston/logger'>;
}
declare module 'winston/lib/winston/transports.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports'>;
}
declare module 'winston/lib/winston/transports/console.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/console'>;
}
declare module 'winston/lib/winston/transports/file.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/file'>;
}
declare module 'winston/lib/winston/transports/http.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/http'>;
}
declare module 'winston/lib/winston/transports/memory.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/memory'>;
}
declare module 'winston/lib/winston/transports/transport.js' {
  declare module.exports: $Exports<'winston/lib/winston/transports/transport'>;
}
declare module 'winston/test/helpers.js' {
  declare module.exports: $Exports<'winston/test/helpers'>;
}
declare module 'winston/test/transports/console-test.js' {
  declare module.exports: $Exports<'winston/test/transports/console-test'>;
}
declare module 'winston/test/transports/file-archive-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-archive-test'>;
}
declare module 'winston/test/transports/file-maxfiles-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-maxfiles-test'>;
}
declare module 'winston/test/transports/file-maxsize-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-maxsize-test'>;
}
declare module 'winston/test/transports/file-open-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-open-test'>;
}
declare module 'winston/test/transports/file-stress-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-stress-test'>;
}
declare module 'winston/test/transports/file-tailrolling-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-tailrolling-test'>;
}
declare module 'winston/test/transports/file-test.js' {
  declare module.exports: $Exports<'winston/test/transports/file-test'>;
}
declare module 'winston/test/transports/http-test.js' {
  declare module.exports: $Exports<'winston/test/transports/http-test'>;
}
declare module 'winston/test/transports/memory-test.js' {
  declare module.exports: $Exports<'winston/test/transports/memory-test'>;
}
declare module 'winston/test/transports/transport.js' {
  declare module.exports: $Exports<'winston/test/transports/transport'>;
}
