version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8087:8080"
  testing:
    image: 'drupaldocker/drush:8-alpine'
    environment:
      # Make sure to run lagoon with properly configured hiera repo
      # otherwise the script will not find any data for the sitegroup
      - AMAZEEIO_OVERRIDE_SITEGROUP=credentialtest
      - AMAZEEIO_OVERRIDE_API_ENDPOINT=http://api:3000/graphql
      - AMAZEEIO_OVERRIDE_JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzc2hLZXkiOiJBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFDNWI5QXdiNml3V1J6MXorUUR3TGxTdnRweGcvN3BSN1JmK2tKVDNraFFHaUx1WDRRazJhRENydDFmS25kanlVdWo1NW9jUmM4T2xFeHJBOEZQZlpicG5mYU5YZlZoOVRseWJoaklXVUh0TGJjOWdpQ29EdWlWMlRFYjZaVy9lc0tsVnRXb216Zlkvbmp3UEF1WEVVMmkzajVZeFZRdVoweStBTjR5Y2E0VjF5N3kyQmxVT3ZwNXFTdnovOFBjQkplZ2FvZXNTU3VGcFFXQ1I3ODgvaTBzVVJKaWFHNit0Wk4rYkdWU25KZ3RiWFFKdmMwcjQ1YXUzUEw1anlNY0FwYkhPQ0RRVUlpV3lDNmlwVzJFSVlUVUJWTzgwUVZFanltbUJacFpFUWwvMERRUEV6QmRxQ2k0WDR3bXdob2FuN2hRSlE3ZE5kcW1STCtXNEw3NXlQTnluZ05nSlZOVGxJWE9IWGV2cE5za0gvL0hVbHdFcDRXUEh1VDc2QlpUM2NxMVJDYXRuNmlNc0Zpd3BFU2s5eHlEYkVWUGZ4S0FyNzdjUnBGSUh1SmQ3YW1EalRrNy9LUDBQVGxpTzJWaUN5akR1ZGlhandOaDdYbVkwWnFZcmhISTE2ZWJUU0VTRHNsaDBhMEpsWnZXbFlhNHhEQkt0S3dmSU5ScmNyWW11WVV6U0Y3d243RjFvNDVjSFoya3VmdGlvT1FoTE5neDBMcXp0Uk1uM1JCb2VHM1FIYnhtdjlXZk8vMGhIYTRGZGtRTEVyRWR6RU05SlI0V2V3Um5oMDRkY2plalgxZGFXS2JvMlg4bmRhQ2MwQnZkTkRML0hwU2dxZkNuSjJObHE0cE02UG9ta3ZkcDV3VFdwWndDakRsMDhVZ3R0QUZyUXdqWW9CeTlVcFVtRFE9PSIsImlzcyI6ImF1dGgtc2VydmVyLmRldiIsInJvbGUiOiJkcnVzaCIsImF1ZCI6ImFwaS5kZXYiLCJpYXQiOjE1MDQxNzYyMDh9.MabPlSIRC-heC35MRZrYXdRDvUsPuBCjOWNAufq1k1c
      #- AMAZEEIO_DEBUG=true
      #- AMAZEEIO_IGNORE_DRUSHCACHE=true
    volumes:
      - './web/aliases.drushrc.php.stub:/etc/drush/aliases.drushrc.php'
    networks:
      - lagoon_default
networks:
  lagoon_default:
    external: true
