import { MockList } from '@graphql-tools/mock';
import { faker } from '@faker-js/faker';
import { packages } from './data/mock-data';

// The mocks object is an Apollo Resolver Map where each mock function has the
// following definition: (parent, args, context, info) => {}
// See https://www.apollographql.com/docs/graphql-tools/mocking/
// https://www.apollographql.com/docs/apollo-server/data/data/#resolver-map
//
// This file should closely match the TypeDefs.js.
// @TODO Prevent mocked values from diverging from defined values in typeDefs.
//   Maybe split up tyepDefs, resolvers and mocks into folders per API concept?

// Allow consumer to generate consistent results by seeding faker.
export const seed = (value = 123) => faker.seed(value);

// Helper function for dates that should be clustered near each other.
const addTime = (originalDate, hoursLimit) => {
  const date = new Date(originalDate);
  date.setTime(
    date.getTime()
    + faker.number.int(hoursLimit*60*60*1000)
  );
  return date.toISOString();
};

// Helper function to build an array of a given schema.
export const generator = (schema, min = 1, max) => {
  max = max || min;
  return Array.from({
    length: faker.number.int({
      min,
      max,
    }),
  }).map(() => {
    const innerGen = (anySchema) => Object.keys(anySchema).reduce((entity, key) => {
      if (Object.prototype.toString.call(anySchema[key]) === '[object Object]') {
        entity[key] = innerGen(anySchema[key]);
        return entity;
      }
      entity[key] = faker.helpers.fake(anySchema[key]);

      return entity;
    }, {});

    return innerGen(schema());
  });
};

//
// 'scalar' and 'enum' mocks from typeDefs.
//
const mocks = {
  Date: () => faker.date.between({from: '2018-11-01T00:00:00', to: '2019-10-31T23:59:59'}).toISOString(),
  JSON: () => ({ id: faker.number.int(), currency: 'usd' }),
  SshKeyType: () => faker.helpers.arrayElement(['ssh_rsa', 'ssh_ed25519','ecdsa_sha2_nistp256','ecdsa_sha2_nistp384','ecdsa_sha2_nistp521']),
  DeployType: () => faker.helpers.arrayElement(['branch', 'pullrequest', 'promote']),
  EnvType: () => faker.helpers.arrayElement(['production', 'development']),
  NotificationType: () => faker.helpers.arrayElement(['slack', 'rocketchat', 'microsoftteams', 'email', 'webhook']),
  DeploymentStatusType: () => faker.helpers.arrayElement(['new', 'pending', 'running', 'cancelled', 'error', 'failed', 'complete']),
  EnvVariableType: () => faker.helpers.arrayElement(['project', 'environment']),
  EnvVariableScope: () => faker.helpers.arrayElement(['build', 'runtime', 'global', 'container_registry']),
  TaskStatusType: () => faker.helpers.arrayElement(['active', 'succeeded', 'failed']),
  RestoreStatusType: () => faker.helpers.arrayElement(['pending', 'successful', 'failed']),
  EnvOrderType: () => faker.helpers.arrayElement(['name', 'updated']),
  ProjectOrderType: () => faker.helpers.arrayElement(['name', 'created']),
  ProjectAvailability: () => faker.helpers.arrayElement(['standard', 'high']),
  GroupRole: () => faker.helpers.arrayElement(['guest', 'reporter', 'developer', 'maintainer', 'owner']),
  OrganizationRole: () => faker.helpers.arrayElement(['OWNER', 'VIEWER']),
  PlatformRole: () => faker.helpers.arrayElement(['OWNER', 'VIEWER']),
  AuditSource: () => faker.helpers.arrayElement(['API', 'CLI', 'UI']),
  RetentionPolicyType: () => faker.helpers.arrayElement(['HARBOR', 'HISTORY']),
  HistoryRetentionType: () => faker.helpers.arrayElement(['COUNT', 'DAYS', 'MONTHS']),
  RouteSource: () => faker.helpers.arrayElement(['API', 'YAML', 'AUTOGENERATED']),
  RouteType: () => faker.helpers.arrayElement(['STANDARD', 'ACTIVE', 'STANDBY']),
  RouteInsecure: () => faker.helpers.arrayElement(['Allow', 'Redirect', 'None']),
};

//
// 'type' mocks from typeDefs.
//

mocks.File = () => {
  const name = faker.system.commonFileName('tgz');
  return {
    id: faker.number.int(),
    filename: name,
    download: `/download/${name}`,
    created: mocks.Date(),
  };
};

mocks.SshKey = () => ({
  id: faker.number.int(),
  name: `${faker.person.firstName()} SSH key`,
  keyValue: faker.string.uuid(),
  keyType: mocks.SshKeyType(),
  keyFingerprint: faker.string.uuid(),
  created: mocks.Date(),
});

mocks.User = (parent, args = {}, context, info) => {
  const firstName = faker.person.firstName();
  const lastName = faker.person.lastName();
  const user = {
    id: faker.number.int(),
    email: faker.internet.email({firstName, lastName}),
    firstName,
    lastName,
    comment: faker.lorem.words(5),
    gitlabId: faker.number.int(),
    sshKeys: [ mocks.SshKey() ],
    groups: [],
  };
  return {
    ...user,
    groups: args.hasOwnProperty('groups')
      ? args.groups
      : [mocks.Group(null, {user})],
  }
};

mocks.GroupMembership = (parent, args = {}, context, info) => ({
  user: args.hasOwnProperty('user')
    ? args.user
    : mocks.User(null, {groups: []}),
  role: mocks.GroupRole(),
});

mocks.Group = (parent, args = {}, context, info) => {
  const user = args.hasOwnProperty('user')
    ? args.user
    : mocks.User(null, {groups: []});
  const user2 = mocks.User(null, {groups: []});

  const group = {
    id: faker.number.int(),
    name: faker.word.sample(),
    // Only mock nested groups when not asked for a user-specific group.
    groups: !args.hasOwnProperty('user')
      ? [mocks.Group(null, {user: mocks.User(null, {groups: []})})]
      : [],
    members: [
      mocks.GroupMembership(null, {user}),
      mocks.GroupMembership(null, {user: user2}),
    ],
  };

  // Add a reference to the group to all of its members.
  user.groups.push(group);
  user2.groups.push(group);

  return group;
};

//mocks.Group = mocks.GroupInterface;

mocks.OrgUser = () => ({
  id: faker.string.uuid(),
  email: faker.internet.email(),
  firstName: faker.person.firstName(),
  lastName: faker.person.lastName(),
  comment: faker.lorem.words(3),
  organizationRole: mocks.OrganizationRole(),
  has2faEnabled: faker.helpers.arrayElement([true, false]),
  isFederatedUser: false,
});

mocks.OrgGroup = () => ({
  id: faker.string.uuid(),
  name: faker.word.sample(),
  type: 'group',
  groups: [],
  members: [],
  memberCount: faker.number.int({ min: 1, max: 20 }),
  projects: [],
  organization: faker.number.int({ min: 1, max: 10 }),
});

mocks.OrgProject = () => ({
  id: faker.number.int(),
  name: `${faker.company.catchPhraseAdjective()} ${faker.company.bsNoun()}`.replace(/[^a-zA-Z0-9]/g, '').toLowerCase(),
  organization: faker.number.int({ min: 1, max: 10 }),
  gitUrl: `git@example.com/org/${faker.word.sample()}.git`,
  groups: [],
  groupCount: faker.number.int({ min: 0, max: 5 }),
  notifications: [],
  retentionPolicies: [],
  metadata: {},
});

mocks.OrgEnvironment = () => ({
  id: faker.number.int(),
  name: faker.helpers.arrayElement(['main', 'staging', 'development']),
  project: mocks.OrgProject(),
  deployType: 'branch',
  deployHeadRef: 'main',
  deployTitle: 'main',
  autoIdle: 1,
  environmentType: 'production',
  openshiftProjectName: `org-project-main`,
  kubernetesNamespaceName: `org-project-main`,
  updated: mocks.Date(),
  created: mocks.Date(),
  deleted: '0000-00-00 00:00:00',
  route: 'https://org-project.example.com',
  routes: 'https://org-project.example.com',
  services: [ mocks.EnvironmentService() ],
  openshift: mocks.Openshift(),
  kubernetes: mocks.Kubernetes(),
});

mocks.OrganizationNotification = () => ({
  name: 'org-notification',
  type: mocks.NotificationType(),
});

mocks.Organization = () => ({
  id: faker.number.int(),
  name: faker.word.sample() + '-org',
  friendlyName: faker.company.name(),
  description: faker.lorem.sentence(),
  quotaProject: faker.number.int({ min: 5, max: 50 }),
  quotaGroup: faker.number.int({ min: 5, max: 20 }),
  quotaNotification: faker.number.int({ min: 5, max: 20 }),
  quotaEnvironment: faker.number.int({ min: 10, max: 100 }),
  quotaRoute: faker.number.int({ min: 10, max: 100 }),
  deployTargets: [ mocks.Openshift() ],
  projects: [ mocks.OrgProject(), mocks.OrgProject() ],
  environments: [],
  groups: [ mocks.OrgGroup() ],
  owners: [ mocks.OrgUser() ],
  notifications: [ mocks.Notification() ],
  created: mocks.Date(),
  envVariables: [],
  retentionPolicies: [],
});

// Note: `me` query returns a User type – no separate mocks.Me needed

mocks.Openshift = () => ({
  id: faker.number.int(),
  name: 'ci-local',
  consoleUrl: 'https://192.168.99.100:8443/',
  token: faker.string.uuid(),
  routerPattern: '${project}.${branch}.192.168.99.100.xip.io',
  projectUser: faker.internet.userName(),
  sshHost: '192.168.99.1',
  sshPort: '22',
  created: mocks.Date(),
  friendlyName: 'Local CI',
  cloudProvider: faker.helpers.arrayElement(['aws', 'gcp', 'azure']),
  cloudRegion: faker.helpers.arrayElement(['us-east-1', 'eu-west-1', 'ap-southeast-2']),
});

mocks.Kubernetes = () => ({
  id: faker.number.int(),
  name: faker.word.sample() + '-k8s',
  consoleUrl: 'https://192.168.99.100:6443/',
  token: faker.string.uuid(),
  routerPattern: '${project}.${branch}.192.168.99.100.xip.io',
  sshHost: '192.168.99.1',
  sshPort: '22',
  created: mocks.Date(),
  friendlyName: 'Local K8s',
  cloudProvider: faker.helpers.arrayElement(['aws', 'gcp', 'azure']),
  cloudRegion: faker.helpers.arrayElement(['us-east-1', 'eu-west-1', 'ap-southeast-2']),
});

mocks.NotificationMicrosoftTeams = () => ({
  id: faker.number.int(),
  name: 'amazeeio--lagoon-local-ci',
  webhook: 'https://amazeeio.teams.microsoft.com/hooks/ikF5XMohDZK7KpsZf/c9BFBt2ch8oMMuycoERJQMSLTPo8nmZhg2Hf2ny68ZpuD4Kn',
});

mocks.NotificationRocketChat = () => ({
  id: faker.number.int(),
  name: 'amazeeio--lagoon-local-ci',
  webhook: 'https://amazeeio.rocket.chat/hooks/ikF5XMohDZK7KpsZf/c9BFBt2ch8oMMuycoERJQMSLTPo8nmZhg2Hf2ny68ZpuD4Kn',
  channel: 'lagoon-local-ci'
});

mocks.NotificationSlack = () => ({
  id: faker.number.int(),
  name: 'amazeeio--lagoon-local-ci',
  webhook: 'https://amazeeio.slack.com/hooks/ikF5XMohDZK7KpsZf/c9BFBt2ch8oMMuycoERJQMSLTPo8nmZhg2Hf2ny68ZpuD4Kn',
  channel: 'lagoon-local-ci'
});

mocks.NotificationEmail = () => ({
  id: faker.number.int(),
  name: 'amazeeio--lagoon-local-ci',
  emailAddress: faker.internet.email(),
});

mocks.NotificationWebhook = () => ({
  id: faker.number.int(),
  name: 'amazeeio--lagoon-local-ci',
  webhook: 'https://amazeeio.example.com/hooks/ikF5XMohDZK7KpsZf/c9BFBt2ch8oMMuycoERJQMSLTPo8nmZhg2Hf2ny68ZpuD4Kn',
  contentType: 'application/json',
  notificationSeverityThreshold: faker.helpers.arrayElement(['NONE', 'UNKNOWN', 'NEGLIGIBLE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']),
});

mocks.UnassignedNotification = () => ({
  id: faker.number.int(),
  name: 'unassigned--local-ci',
  type: mocks.NotificationType(),
});

mocks.Notification = () => {
  switch (mocks.NotificationType()) {
    case 'email':
      return mocks.NotificationEmail();
    case 'microsoftteams':
      return mocks.NotificationMicrosoftTeams();
    case 'rocketchat':
      return mocks.NotificationRocketChat();
    case 'slack':
      return mocks.NotificationSlack();
    case 'webhook':
      return mocks.NotificationWebhook();
  }
};

mocks.Project = (parent, args = {}, context, info) => {
  const name = `${faker.company.catchPhraseAdjective()} ${faker.company.bsNoun()}`.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
  const project = {
    id: faker.number.int(),
    name,
    gitUrl: faker.helpers.arrayElement([`git@example.com/${name}/${faker.company.bsNoun()}.git`, `https://example.com/${name}/${faker.company.bsNoun()}.git`]),
    availability: mocks.ProjectAvailability(),
    privateKey: `-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEA+o[...]P0yoL8BoQQG2jCvYfWh6vyglQdrDYx/o6/8ecTwXokKKh6fg1q
-----END RSA PRIVATE KEY-----`,
    subfolder: '',
    notifications: [mocks.Notification()],
    branches: faker.helpers.arrayElement(['true', 'false', '^(master|staging)$']),
    pullrequests: faker.helpers.arrayElement(['true', 'false', '[BUILD]']),
    productionEnvironment: 'master',
    autoIdle: faker.helpers.arrayElement([0, 1]),
    storageCalc: faker.helpers.arrayElement([0, 1]),
    problemsUi: 1,
    factsUi: 1,
    openshift: mocks.Openshift(),
    developmentEnvironmentsLimit: 10,
    environments: [],
    created: mocks.Date(),
    envVariables: [ mocks.EnvKeyValue() ],
    // groups: [ mocks.Group() ],
  };
  return {
    ...project,
    environments: args.hasOwnProperty('environments') ? args.environments : mocks.Query().allEnvironments(null, { project }),
  };
};

mocks.Environment = (parent, args = {}, context, info) => {
  const name = args.hasOwnProperty('name')
    ? args.name
    : faker.helpers.arrayElement(['master', 'staging', 'development', 'pr-42', 'pr-100', 'pr-175']);
  let deployType, deployBaseRef, deployHeadRef;
  if (/^pr\-/.test(name)) {
    deployType = 'pullrequest';
    deployBaseRef = 'target';
    deployHeadRef = 'source';
  } else {
    deployType = 'branch';
    deployBaseRef = name;
    deployHeadRef = 'source';
  }
  const created = mocks.Date();
  const updated = addTime(created, 48);
  const deleted = addTime(updated, 24);
  const project = args.hasOwnProperty('project') ? args.project : mocks.Project(null, { environment: {} });

  const environment = {
    id: faker.number.int(),
    name,
    project,
    deployType,
    deployBaseRef,
    deployHeadRef,
    deployTitle: name,
    autoIdle: faker.helpers.arrayElement([0, 1]),
    environmentType: name === 'master' ? 'production' : 'development',
    openshiftProjectName: `${project.name}-${name}`.toLowerCase(),
    updated,
    created,
    deleted,
    hoursMonth: mocks.EnvironmentHoursMonth(),
    storages: [],
    storageMonth: mocks.EnvironmentStorageMonth(),
    hitsMonth: mocks.EnvironmentHitsMonth(),
    envVariables: [ mocks.EnvKeyValue() ],
    route: name === 'master' ? `https://${project.name}.org` : `https://${name}.${project.name}.org`,
    routes: `https://${project.name}.org,https://varnish-${project.name}-org-prod.us.amazee.io,https://nginx-${project.name}-org-prod.us.amazee.io`,
    monitoringUrls: null,
    deployments: [
      mocks.Deployment(null, {environment: { created: new Date(mocks.Date()) }}),
      mocks.Deployment(null, {environment: {}})
    ],
    backups: [],
    tasks: [],
    problems: [],
    facts: [],
    services: [ mocks.EnvironmentService(), mocks.EnvironmentService(), mocks.EnvironmentService() ],
  };

  return {
    ...environment,
    storages: [ mocks.EnvironmentStorage(null, {environment}) ],
    deployments: args.hasOwnProperty('deployments') ? args.deployments : [
      mocks.Deployment(null, {environment} ),
      mocks.Deployment(null, {environment} )
    ],
    problems: args.hasOwnProperty('problems') ? args.problems : [
      mocks.Problem(null, {source: "Drutiny", severity: "CRITICAL"}),
      mocks.Problem(null, {source: "Trivy", severity: "MEDIUM"}),
      mocks.Problem(null, {source: "Drutiny", severity: "HIGH"}),
      mocks.Problem(null, {source: "OWASP ZAP", severity: "LOW"}),
      mocks.Problem(),
      mocks.Problem()
    ],
    facts: args.hasOwnProperty('facts') ? args.facts : [
      mocks.Fact(null, { name: "php-version", value: faker.helpers.arrayElement(['7.4.1', '7.2.1', '7.1.1', '8.1.0']), source: "php-version", category: "Programming language", keyFact: true} ),
      mocks.Fact(null, { name: "drupal-core", value: "9.0.12", source: "drupal-version", category: "Framework", keyFact: true} ),
      mocks.Fact(null, { name: "Lagoon", value: " 21.3.0", source: "env", category: "Platform", keyFact: true} ),
      mocks.Fact(null, { name: "site-code-status", value: faker.helpers.arrayElement(['200', '404', '403', '301', '504', '503']), source: "curl", category: "Performance", keyFact: true} ),
      mocks.Fact(null, { name: "lagoon-category", value: "saas", source: "saas", category: "Lagoon", keyFact: true} ),
      mocks.Fact(),
      mocks.Fact()
    ],
    backups: args.hasOwnProperty('backups') ? args.backups : [ mocks.Backup(null, {environment}) ],
    tasks: args.hasOwnProperty('tasks') ? args.tasks : [ mocks.Task(null, {environment}) ],
  };
};

mocks.EnvironmentHitsMonth = () => ({
  total: faker.number.int(),
});

mocks.EnvironmentStorage = (parent, args = {}, context, info) => ({
  id: faker.number.int(),
  environment: args.hasOwnProperty('environment') ? { id: args.environment.id } : { id: mocks.Environment().id },
  persistentStorageClaim: '',
  kibUsed: faker.number.float({ multipleOf: 0.001 }), // Float
  updated: mocks.Date(),
});

mocks.EnvironmentStorageMonth = () => {
  const date = new Date(mocks.Date());
  return {
    month: `${date.getFullYear()}-${date.getMonth() + 1}`,
    kibUsed: faker.number.float({ multipleOf: 0.001 }),
  };
};

mocks.EnvironmentHoursMonth = () => {
  const date = new Date(mocks.Date());
  return {
    month: `${date.getFullYear()}-${date.getMonth() + 1}`,
    hours: faker.number.int({ max: 24*30 }),
  };
};

mocks.EnvironmentService = () => ({
  id: faker.number.int(),
  name: faker.helpers.arrayElement(['cli', 'nginx', 'mariadb', 'solr', 'varnish', 'php']),
});

mocks.Fact = (parent, args = {}, context, info) => {
  const id = `${faker.number.int({min: 0, max: 99999})}`;
  const name = args.hasOwnProperty('name') ? args.name : faker.helpers.arrayElement(['drupal-version', 'drush-version', 'admin_toolbar', 'drupal-core', 'laravel', 'composer-version']);
  const value = args.hasOwnProperty('value') ? args.value : faker.helpers.arrayElement(['8.0.1', '9.0.1', '3.2.1', '10.20.2', '4.3.4']);
  const source = args.hasOwnProperty('source') ? args.source : faker.helpers.arrayElement(['drush_pml', 'drush_status', 'http_header', 'php-version', 'env']);
  const category = args.hasOwnProperty('category') ? args.category : faker.helpers.arrayElement(['Application', 'Framework', 'Docker configuration', 'Drupal configuration', 'Lagoon', 'Platform', 'Programming language']);
  const description = faker.lorem.paragraph();
  const environment = `${faker.number.int({min:0, max:5})}`;
  const keyFact = args.hasOwnProperty('keyFact') ? args.keyFact : false;
  const type = args.hasOwnProperty('type') ? args.type : 'TEXT';

  const references = [{
    id: faker.number.int(),
    fid: faker.number.int(),
    name: faker.helpers.arrayElement([
      ['nginx.company.amazee.io'], ['cli'], ['solr'], ['php'], ['backend.company.amazee.io']
    ])
  }];

  return {
    id: id,
    name: name,
    value: value,
    source: source,
    category: category,
    description,
    environment,
    keyFact,
    type,
    references
  };
};

mocks.Backup = (parent, args = {}, context, info) => {
  const date = mocks.Date();
  const backupId = faker.string.uuid();
  return {
    id: faker.number.int(),
    environment: args.hasOwnProperty('environment') ? { id: args.environment.id } : { id: mocks.Environment().id },
    source: faker.helpers.arrayElement(['files', 'mariadb']),
    backupId,
    created: date,
    deleted: addTime(date, 24),
    restore: mocks.Restore(null, {backupId}),
  };
};

mocks.Restore = (parent, args = {}, context, info) => {
  const backupId = args.hasOwnProperty('backupId')
    ? args.backupId
    : faker.number.int();
  return {
    id: faker.number.int(),
    backupId,
    status: mocks.RestoreStatusType(),
    restoreLocation: `/restore/${backupId}`,
    created: mocks.Date(),
  };
};

mocks.Deployment = (parent, args = {}, context, info) => {
  const id = faker.number.int();
  const created = args.hasOwnProperty('created') ? args.created : mocks.Date();
  const started = addTime(created, .5);
  const completed = addTime(started, .75);

  return {
    id,
    name: `build-${id}`,
    status: mocks.DeploymentStatusType(),
    created,
    started,
    completed,
    environment: args.hasOwnProperty('environment') ? args.environment : mocks.Environment(null, {deployments: []} ),
    remoteId: faker.number.int(),
    buildLog: 'Buildem logem ipsum.',
  };
};

mocks.EnvKeyValue = () => ({
  id: faker.number.int(),
  scope: mocks.EnvVariableScope(),
  name: 'LAGOON_API_VARIABLE_PROJECT',
  value: '4A65DC68F2',
});

mocks.Task = (parent, args = {}, context, info) => {
  const name = faker.helpers.arrayElement(['Site Status', 'Drupal Archive']);
  const created = mocks.Date();
  const started = addTime(created, 0.125);
  const completed = addTime(created, 1.7);
  return {
    id: args.hasOwnProperty('id') ? args.id : faker.number.int(),
    name,
    status: mocks.TaskStatusType(),
    created,
    started,
    completed,
    environment: args.hasOwnProperty('environment') ?  args.environment : mocks.Environment(),
    service: 'cli',
    command: name === 'Site Status' ? 'drush status' : 'drush archive-dump',
    remoteId: faker.string.uuid(),
    logs: 'Taskem logem ipsum.',
    files: [ mocks.File() ],
  };
};

mocks.DeployTargetConfig = () => ({
  id: faker.number.int(),
  project: null, // avoid circular; set at call site if needed
  weight: faker.number.int({ min: 1, max: 100 }),
  branches: faker.helpers.arrayElement(['true', 'false', '^(main|master)$']),
  pullrequests: faker.helpers.arrayElement(['true', 'false']),
  deployTarget: mocks.Openshift(),
});

mocks.AuditLog = () => ({
  id: faker.number.int(),
  usid: faker.string.uuid(),
  emailAddress: faker.internet.email(),
  resourceId: `${faker.number.int({ min: 1, max: 9999 })}`,
  resourceType: faker.helpers.arrayElement(['PROJECT', 'ENVIRONMENT', 'GROUP', 'USER', 'ORGANIZATION']),
  resourceDetails: faker.lorem.words(3),
  linkedResourceId: null,
  linkedResourceType: null,
  linkedResourceDetails: null,
  auditEvent: faker.helpers.arrayElement(['addProject', 'deleteEnvironment', 'addUser', 'updateProject']),
  impersonatorId: null,
  impersonatorUsername: null,
  ipAddress: faker.internet.ipv4(),
  source: mocks.AuditSource(),
  created: mocks.Date(),
  organizationId: faker.number.int({ min: 1, max: 10 }),
});

mocks.Route = () => ({
  id: faker.number.int(),
  domain: `${faker.word.sample()}.${faker.internet.domainSuffix()}`,
  service: faker.helpers.arrayElement(['nginx', 'varnish', 'node']),
  tlsAcme: faker.helpers.arrayElement([true, false]),
  insecure: mocks.RouteInsecure(),
  primary: faker.helpers.arrayElement([true, false]),
  source: mocks.RouteSource(),
  type: mocks.RouteType(),
  annotations: [],
  pathRoutes: [],
  alternativeNames: [],
  updated: mocks.Date(),
  created: mocks.Date(),
});

mocks.AdvancedTaskDefinitionArgument = () => ({
  id: faker.number.int(),
  name: faker.word.sample(),
  displayName: faker.word.sample(),
  type: faker.helpers.arrayElement(['STRING', 'ENVIRONMENT_SOURCE_NAME', 'ENVIRONMENT_SOURCE_NAME_EXCLUDE_SELF']),
  defaultValue: '',
  optional: faker.helpers.arrayElement([true, false]),
  range: [],
});

mocks.AdvancedTaskDefinitionCommand = () => ({
  id: faker.number.int(),
  name: faker.word.sample() + '-task',
  description: faker.lorem.sentence(),
  confirmationText: '',
  type: 'COMMAND',
  service: 'cli',
  command: 'drush ' + faker.word.sample(),
  groupName: '',
  environment: null,
  project: null,
  systemWide: false,
  permission: faker.helpers.arrayElement(['PRODUCTION', 'DEVELOPMENT', 'GUEST']),
  deployTokenInjection: false,
  projectKeyInjection: false,
  adminOnlyView: false,
  advancedTaskDefinitionArguments: [],
  created: mocks.Date(),
  deleted: '0000-00-00 00:00:00',
});

mocks.AdvancedTaskDefinitionImage = () => ({
  id: faker.number.int(),
  name: faker.word.sample() + '-image-task',
  description: faker.lorem.sentence(),
  confirmationText: '',
  type: 'IMAGE',
  image: `uselagoon/${faker.word.sample()}:latest`,
  service: 'cli',
  groupName: '',
  environment: null,
  project: null,
  systemWide: false,
  permission: faker.helpers.arrayElement(['PRODUCTION', 'DEVELOPMENT', 'GUEST']),
  deployTokenInjection: false,
  projectKeyInjection: false,
  adminOnlyView: false,
  advancedTaskDefinitionArguments: [ mocks.AdvancedTaskDefinitionArgument() ],
  created: mocks.Date(),
  deleted: '0000-00-00 00:00:00',
});

mocks.HarborRetentionPolicy = () => ({
  id: faker.number.int(),
  name: faker.word.sample() + '-harbor-policy',
  configuration: {
    enabled: true,
    rules: [{ name: 'retain-last-10', pattern: '**', latestPulled: 10 }],
    schedule: '0 0 * * *',
  },
  created: mocks.Date(),
  updated: mocks.Date(),
  source: faker.helpers.arrayElement(['project', 'organization']),
});

mocks.HistoryRetentionPolicy = () => ({
  id: faker.number.int(),
  name: faker.word.sample() + '-history-policy',
  configuration: {
    enabled: true,
    deploymentHistory: 10,
    deploymentType: 'COUNT',
    taskHistory: 5,
    taskType: 'COUNT',
  },
  created: mocks.Date(),
  updated: mocks.Date(),
  source: faker.helpers.arrayElement(['project', 'organization']),
});

mocks.Problem = (parent, args = {}, context, info) => {
    const recentYear = faker.helpers.arrayElement(['2019', '2020']);
    const vuln_id = `CVE-${recentYear}-${faker.number.int({min: 1000, max: 99999})}`;
    const source = faker.helpers.arrayElement(['Lighthouse', 'Drutiny', 'Trivy', 'OWASP ZAP', 'Script']);
    // const created = faker.date.between('2019-10-01 00:00:00', '2020-03-31 23:59:59').toUTCString();
    const associatedPackage = faker.helpers.arrayElement(packages);
    // const version = `${faker.number.int(4)}.${faker.number.int(9)}.${faker.number.int(49)}`;
    // const fixedVersion = `${version}+deb8u${faker.number.int(9)}`;
    const severity = faker.helpers.arrayElement(['UNKNOWN', 'NEGLIGIBLE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);
    const description = faker.lorem.paragraph();
    const links = `https://security-tracker.debian.org/tracker/${vuln_id}`;
    const severityScore = `0.${faker.number.int({min:1, max:9})}`;
    const data =  JSON.stringify({id: `${faker.number.int({min:1, max:100})}`}, null, '\t');

    return {
      identifier: vuln_id,
      severity: args.hasOwnProperty('severity') ? args.severity : severity,
      source: args.hasOwnProperty('source') ? args.source : source,
      severityScore: severityScore,
      associatedPackage: associatedPackage,
      description,
      links,
      data
    };
};


//
// Query 'type' mock from typeDefs.
//
mocks.Query = () => ({
  // User / Auth
  me: () => mocks.User(null, { groups: [] }),
  userBySshKey: () => mocks.User(),
  userByEmail: () => mocks.User(),
  userBySshFingerprint: () => mocks.User(),
  userByEmailAndOrganization: () => mocks.OrgUser(),
  userCanSshToEnvironment: () => true,
  usersByOrganization: () => new MockList(3, () => mocks.OrgUser()),
  allUsers: () => new MockList(5, () => mocks.User()),
  allPlatformUsers: () => new MockList(3, () => mocks.User()),

  // Projects
  projectByName: () => mocks.Project(),
  projectByGitUrl: () => mocks.Project(),
  projectsByMetadata: () => [mocks.Project(), mocks.Project()],
  allProjects: () => new MockList(5, () => mocks.Project()),
  projectsByFactSearch: () => ({ count: 3, projects: [mocks.Project(), mocks.Project(), mocks.Project()] }),
  environmentsByFactSearch: () => ({ count: 2, environments: [mocks.Environment(), mocks.Environment()] }),

  // Groups
  groupByName: () => mocks.Group(),
  groupByNameAndOrganization: () => mocks.Group(),
  allGroups: () => new MockList(9),
  allProjectsInGroup: () => new MockList(5),

  // Environments
  environmentByName: () => mocks.Environment(),
  environmentByOpenshiftProjectName: () => mocks.Environment(),
  environmentById: () => mocks.Environment(),
  environmentByKubernetesNamespaceName: () => mocks.Environment(),
  allEnvironments: (parent, args = {}, context, info) => {
    const project = args.hasOwnProperty('project')
      ? args.project
      : mocks.Project(null, {environments: []});
    return [
      mocks.Environment(null, {project, name: 'master'}),
      mocks.Environment(null, {project, name: 'staging'}),
      mocks.Environment(null, {project, name: 'development'}),
      mocks.Environment(null, {project, name: 'pr-' + faker.number.int({min: 1, max: 50})}),
      mocks.Environment(null, {project, name: 'pr-' + faker.number.int({min: 51, max: 100})}),
      mocks.Environment(null, {project, name: 'pr-' + faker.number.int({min: 101, max: 150})}),
    ];
  },
  environmentsByKubernetes: () => new MockList(5, () => mocks.Environment()),

  // Deploy targets
  allOpenshifts: () => new MockList(9),
  allKubernetes: () => new MockList(3, () => mocks.Kubernetes()),

  // Notifications
  allNotifications: () => new MockList(5, () => mocks.Notification()),

  // Deployments
  deploymentByRemoteId: () => mocks.Deployment(),
  deploymentByName: () => mocks.Deployment(),
  deploymentsByBulkId: () => new MockList(3, () => mocks.Deployment()),
  deploymentsByFilter: () => new MockList(10, () => mocks.Deployment()),

  // Tasks
  taskByRemoteId: () => mocks.Task(),
  taskById: () => mocks.Task(),
  taskByTaskName: () => mocks.Task(),

  // Problems
  allProblems: () => new MockList(20),
  problemSources: () => ['Harbor', 'Drutiny', 'Trivy', 'OWASP ZAP'],

  // Organizations
  allOrganizations: () => new MockList(3, () => mocks.Organization()),
  organizationById: () => mocks.Organization(),
  organizationByName: () => mocks.Organization(),
  orgProjectByName: () => mocks.OrgProject(),
  checkBulkImportProjectsAndGroupsToOrganization: () => null,

  // Deploy target configs
  allDeployTargetConfigs: () => [mocks.DeployTargetConfig()],
  deployTargetConfigById: () => mocks.DeployTargetConfig(),
  deployTargetConfigsByDeployTarget: () => [mocks.DeployTargetConfig()],
  deployTargetConfigsByProjectId: () => [mocks.DeployTargetConfig()],

  // Advanced tasks
  allAdvancedTaskDefinitions: () => [mocks.AdvancedTaskDefinitionCommand(), mocks.AdvancedTaskDefinitionImage()],
  advancedTaskDefinitionById: () => mocks.AdvancedTaskDefinitionCommand(),
  advancedTaskDefinitionArgumentById: () => mocks.AdvancedTaskDefinitionArgument(),
  advancedTasksForEnvironment: () => new MockList(3),

  // Backups / Files
  getBackupDownloadLinkByBackupId: () => faker.string.uuid(),
  getDownloadLinkByTaskFileId: () => faker.string.uuid(),
  getTaskFileUploadForm: () => null,

  // Env variables
  getEnvVariablesByProjectEnvironmentName: () => [mocks.EnvKeyValue()],

  // Deprecated org helpers
  getGroupProjectOrganizationAssociation: () => 'success',
  getProjectGroupOrganizationAssociation: () => 'success',

  // Audit logs
  getAuditLogs: () => new MockList(10, () => mocks.AuditLog()),

  // Retention policies
  listAllRetentionPolicies: () => [mocks.HarborRetentionPolicy(), mocks.HistoryRetentionPolicy()],

  // Misc
  lagoonVersion: () => '24.x.x',
});

//
// Mutation 'type' mock from typeDefs.
//
mocks.Mutation = () => ({
  // Environment
  addOrUpdateEnvironment: () => mocks.Environment(),
  updateEnvironment: () => mocks.Environment(),
  updateEnvironmentDeployTarget: () => mocks.Environment(),
  deleteEnvironment: () => faker.helpers.arrayElement(['success', `Error: unknown deploy type ${mocks.DeployType()}`]),
  addOrUpdateEnvironmentStorage: () => mocks.EnvironmentStorage(),
  idleOrUnidleEnvironment: () => mocks.Environment(),

  // Notifications
  addNotificationSlack: () => mocks.NotificationSlack(),
  updateNotificationSlack: () => mocks.NotificationSlack(),
  deleteNotificationSlack: () => faker.helpers.arrayElement(['success', "Can't delete notification linked to projects"]),
  addNotificationRocketChat: () => mocks.NotificationRocketChat(),
  updateNotificationRocketChat: () => mocks.NotificationRocketChat(),
  deleteNotificationRocketChat: () => faker.helpers.arrayElement(['success', "Can't delete notification linked to projects"]),
  addNotificationMicrosoftTeams: () => mocks.NotificationMicrosoftTeams(),
  updateNotificationMicrosoftTeams: () => mocks.NotificationMicrosoftTeams(),
  deleteNotificationMicrosoftTeams: () => faker.helpers.arrayElement(['success', "Can't delete notification linked to projects"]),
  addNotificationEmail: () => mocks.NotificationEmail(),
  updateNotificationEmail: () => mocks.NotificationEmail(),
  deleteNotificationEmail: () => faker.helpers.arrayElement(['success', "Can't delete notification linked to projects"]),
  addNotificationWebhook: () => mocks.NotificationWebhook(),
  updateNotificationWebhook: () => mocks.NotificationWebhook(),
  deleteNotificationWebhook: () => faker.helpers.arrayElement(['success', "Can't delete notification linked to projects"]),
  addNotificationToProject: () => mocks.Project(),
  removeNotificationFromProject: () => mocks.Project(),

  // Deploy targets
  addOpenshift: () => mocks.Openshift(),
  updateOpenshift: () => mocks.Openshift(),
  deleteOpenshift: () => 'success',
  addKubernetes: () => mocks.Kubernetes(),
  updateKubernetes: () => mocks.Kubernetes(),
  deleteKubernetes: () => 'success',

  // Projects
  addProject: () => mocks.Project(),
  updateProject: () => mocks.Project(),
  deleteProject: () => 'success',
  deleteAllProjects: () => 'success',
  updateProjectMetadata: () => mocks.Project(),
  removeProjectMetadataByKey: () => mocks.Project(),

  // SSH keys
  addSshKey: () => mocks.SshKey(),
  updateSshKey: () => mocks.SshKey(),
  deleteSshKey: () => 'success',
  deleteSshKeyById: () => 'success',
  addUserSSHPublicKey: () => mocks.SshKey(),
  updateUserSSHPublicKey: () => mocks.SshKey(),
  deleteUserSSHPublicKey: () => 'success',

  // Users
  addUser: () => mocks.User(),
  updateUser: () => mocks.User(),
  deleteUser: () => 'success',
  resetUserPassword: () => 'success',
  addPlatformRoleToUser: () => mocks.User(),
  removePlatformRoleFromUser: () => mocks.User(),

  // Deployments
  addDeployment: () => mocks.Deployment(),
  deleteDeployment: () => 'success',
  updateDeployment: () => mocks.Deployment(),
  cancelDeployment: () => faker.helpers.arrayElement(['success', 'Deployment not cancelled, reason: Too slow.']),
  deployEnvironmentLatest: () => 'success',
  deployEnvironmentBranch: () => 'success',
  deployEnvironmentPullrequest: () => 'success',
  deployEnvironmentPromote: () => 'success',
  bulkDeployEnvironmentLatest: () => faker.string.uuid(),
  switchActiveStandby: () => 'success',

  // Backups
  addBackup: () => mocks.Backup(),
  deleteBackup: () => 'success',
  deleteRestore: () => mocks.Backup(),
  addRestore: () => mocks.Restore(),
  updateRestore: () => mocks.Restore(),

  // Env variables
  addEnvVariable: () => mocks.EnvKeyValue(),
  addOrUpdateEnvVariableByName: () => mocks.EnvKeyValue(),
  addOrUpdateStorageOnEnvironment: () => mocks.EnvironmentStorage(),
  deleteEnvVariable: () => 'success',
  deleteEnvVariableByName: () => 'success',

  // Tasks
  addTask: () => mocks.Task(),
  taskDrushArchiveDump: () => mocks.Task(),
  taskDrushSqlDump: () => mocks.Task(),
  taskDrushCacheClear: () => mocks.Task(),
  taskDrushCron: () => mocks.Task(),
  taskDrushSqlSync: () => mocks.Task(),
  taskDrushRsyncFiles: () => mocks.Task(),
  taskDrushUserLogin: () => mocks.Task(),
  deleteTask: () => 'success',
  updateTask: () => mocks.Task(),
  cancelTask: () => faker.helpers.arrayElement(['success', 'Task not cancelled, reason: Too slow.']),
  invokeRegisteredTask: () => mocks.Task(),
  uploadFilesForTask: () => mocks.Task(),
  deleteFilesForTask: () => 'success',

  // Services
  setEnvironmentServices: () => [ mocks.EnvironmentService() ],
  addOrUpdateEnvironmentService: () => mocks.EnvironmentService(),
  deleteEnvironmentService: () => 'success',
  stopOrStartEnvironmentService: () => 'success',

  // Groups
  addGroup: () => mocks.Group(),
  updateGroup: () => mocks.Group(),
  deleteGroup: () => 'success',
  addUserToGroup: () => mocks.Group(),
  removeUserFromGroup: () => mocks.Group(),
  addGroupsToProject: () => mocks.Project(),
  removeGroupsFromProject: () => mocks.Project(),

  // Problems
  addProblem: () => mocks.Problem(),
  deleteProblem: () => 'success',
  deleteProblemsFromSource: () => 'success',

  // Facts
  addFact: () => mocks.Fact(),
  addFacts: () => [mocks.Fact(), mocks.Fact()],
  addFactsByName: () => [mocks.Fact()],
  deleteFact: () => 'success',
  deleteFactsFromSource: () => 'success',
  addFactReference: () => mocks.Fact(),
  deleteFactReference: () => 'success',
  deleteAllFactReferencesByFactId: () => 'success',

  // Organizations
  addOrganization: () => mocks.Organization(),
  updateOrganization: () => mocks.Organization(),
  deleteOrganization: () => 'success',
  addAdminToOrganization: () => mocks.Organization(),
  removeAdminFromOrganization: () => mocks.Organization(),
  addGroupToOrganization: () => mocks.Organization(),
  addExistingGroupToOrganization: () => mocks.Organization(),
  addExistingProjectToOrganization: () => mocks.Project(),
  bulkImportProjectsAndGroupsToOrganization: () => null,
  removeProjectFromOrganization: () => 'success',
  addUserToOrganization: () => mocks.Organization(),
  removeUserFromOrganization: () => 'success',
  removeUserFromOrganizationGroups: () => 'success',
  addDeployTargetToOrganization: () => mocks.Organization(),
  removeDeployTargetFromOrganization: () => 'success',

  // Deploy target configs
  addDeployTargetConfig: () => mocks.DeployTargetConfig(),
  updateDeployTargetConfig: () => mocks.DeployTargetConfig(),
  deleteDeployTargetConfig: () => 'success',

  // Routes
  addRouteToProject: () => mocks.Route(),
  updateRouteOnProject: () => mocks.Route(),
  addRouteAlternativeDomains: () => mocks.Route(),
  removeRouteAlternativeDomain: () => mocks.Route(),
  addRouteAnnotation: () => mocks.Route(),
  removeRouteAnnotation: () => mocks.Route(),
  addPathRoutesToRoute: () => mocks.Route(),
  removePathRouteFromRoute: () => mocks.Route(),
  addOrUpdateRouteOnEnvironment: () => mocks.Route(),
  activeStandbyRouteMove: () => mocks.Route(),
  removeRouteFromEnvironment: () => mocks.Route(),
  deleteRoute: () => 'success',
  updateAutogeneratedRouteConfigOnProject: () => null,
  updateAutogeneratedRouteConfigOnEnvironment: () => null,
  removeAutogeneratedRouteConfigFromProject: () => 'success',
  removeAutogeneratedRouteConfigFromEnvironment: () => 'success',

  // Advanced tasks
  addAdvancedTaskDefinition: () => mocks.AdvancedTaskDefinitionCommand(),
  updateAdvancedTaskDefinition: () => mocks.AdvancedTaskDefinitionCommand(),
  deleteAdvancedTaskDefinition: () => 'success',

  // Retention policies
  createHarborRetentionPolicy: () => mocks.HarborRetentionPolicy(),
  updateHarborRetentionPolicy: () => mocks.HarborRetentionPolicy(),
  deleteHarborRetentionPolicy: () => 'success',
  addHarborRetentionPolicyLink: () => 'success',
  removeHarborRetentionPolicyLink: () => 'success',
  createHistoryRetentionPolicy: () => mocks.HistoryRetentionPolicy(),
  updateHistoryRetentionPolicy: () => mocks.HistoryRetentionPolicy(),
  deleteHistoryRetentionPolicy: () => 'success',
  addHistoryRetentionPolicyLink: () => 'success',
  removeHistoryRetentionPolicyLink: () => 'success',
});


//
// Subscription 'type' mock from typeDefs.
// @TODO These subscriptions don't work.
// Possible resources for fixing:
// https://www.apollographql.com/docs/react/data/subscriptions/
// https://spectrum.chat/apollo/subscriptions/how-to-test-component-with-subscribetomore~815325bc-bb27-4d5d-a27f-0788b256e382
//
mocks.Subscription = () => ({
  backupChanged: () => mocks.Backup(),
  deploymentChanged: () => mocks.Deployment(),
  taskChanged: () => mocks.Task(),
});

export default mocks;
